/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as QuestionBankRouteRouteImport } from './routes/question-bank/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as QuestionBankIndexRouteImport } from './routes/question-bank/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as QuestionBankTagsRouteImport } from './routes/question-bank/tags'
import { Route as QuestionBankQuestionsRouteImport } from './routes/question-bank/questions'
import { Route as QuestionBankPracticeRouteImport } from './routes/question-bank/practice'
import { Route as QuestionBankImportExportRouteImport } from './routes/question-bank/import-export'
import { Route as QuestionBankCategoriesRouteImport } from './routes/question-bank/categories'
import { Route as QuestionBankAnalyticsRouteImport } from './routes/question-bank/analytics'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminUserrolenavgroupRouteImport } from './routes/admin/userrolenavgroup'
import { Route as AdminTranslationRouteImport } from './routes/admin/translation'
import { Route as AdminSessionRouteImport } from './routes/admin/session'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRolenavgroupRouteImport } from './routes/admin/rolenavgroup'
import { Route as AdminNavitemRouteImport } from './routes/admin/navitem'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminNavgroupRouteImport } from './routes/admin/navgroup'
import { Route as AdminLogRouteImport } from './routes/admin/log'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminOrganizationIndexRouteImport } from './routes/admin/organization/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiI18nLngRouteImport } from './routes/api/i18n/$lng'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminOrganizationMemberRouteImport } from './routes/admin/organization/member'
import { Route as AdminOrganizationInvitationRouteImport } from './routes/admin/organization/invitation'
import { Route as AdminOrganizationCreateRouteImport } from './routes/admin/organization/create'
import { Route as AdminOrganizationIdRouteImport } from './routes/admin/organization/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDemoSettingsRouteRouteImport } from './routes/_authenticated/demo/settings/route'
import { Route as ApiQuestionBankTagsIndexRouteImport } from './routes/api/question-bank/tags/index'
import { Route as ApiQuestionBankQuestionsIndexRouteImport } from './routes/api/question-bank/questions/index'
import { Route as ApiQuestionBankCategoriesIndexRouteImport } from './routes/api/question-bank/categories/index'
import { Route as ApiDemoTasksIndexRouteImport } from './routes/api/demo/tasks/index'
import { Route as ApiAdminUserIndexRouteImport } from './routes/api/admin/user/index'
import { Route as ApiAdminTranslationIndexRouteImport } from './routes/api/admin/translation/index'
import { Route as ApiAdminSessionIndexRouteImport } from './routes/api/admin/session/index'
import { Route as ApiAdminRoleIndexRouteImport } from './routes/api/admin/role/index'
import { Route as ApiAdminOrganizationIndexRouteImport } from './routes/api/admin/organization/index'
import { Route as ApiAdminNavitemIndexRouteImport } from './routes/api/admin/navitem/index'
import { Route as ApiAdminNavgroupIndexRouteImport } from './routes/api/admin/navgroup/index'
import { Route as ApiAdminMemberIndexRouteImport } from './routes/api/admin/member/index'
import { Route as ApiAdminLogIndexRouteImport } from './routes/api/admin/log/index'
import { Route as ApiAdminInvitationIndexRouteImport } from './routes/api/admin/invitation/index'
import { Route as AuthenticatedDemoUsersIndexRouteImport } from './routes/_authenticated/demo/users/index'
import { Route as AuthenticatedDemoTasksIndexRouteImport } from './routes/_authenticated/demo/tasks/index'
import { Route as AuthenticatedDemoSettingsIndexRouteImport } from './routes/_authenticated/demo/settings/index'
import { Route as AuthenticatedDemoChatsIndexRouteImport } from './routes/_authenticated/demo/chats/index'
import { Route as AuthenticatedDemoAppsIndexRouteImport } from './routes/_authenticated/demo/apps/index'
import { Route as ApiQuestionBankTagsIdRouteImport } from './routes/api/question-bank/tags/$id'
import { Route as ApiQuestionBankQuestionsIdRouteImport } from './routes/api/question-bank/questions/$id'
import { Route as ApiQuestionBankCategoriesIdRouteImport } from './routes/api/question-bank/categories/$id'
import { Route as ApiAdminUserBulkDeleteRouteImport } from './routes/api/admin/user/bulk-delete'
import { Route as ApiAdminUserBulkBanRouteImport } from './routes/api/admin/user/bulk-ban'
import { Route as ApiAdminUserIdRouteImport } from './routes/api/admin/user/$id'
import { Route as ApiAdminTranslationImportRouteImport } from './routes/api/admin/translation/import'
import { Route as ApiAdminTranslationExportRouteImport } from './routes/api/admin/translation/export'
import { Route as ApiAdminTranslationIdRouteImport } from './routes/api/admin/translation/$id'
import { Route as ApiAdminSessionIdRouteImport } from './routes/api/admin/session/$id'
import { Route as ApiAdminRoleIdRouteImport } from './routes/api/admin/role/$id'
import { Route as ApiAdminOrganizationBatchRouteImport } from './routes/api/admin/organization/batch'
import { Route as ApiAdminOrganizationIdRouteImport } from './routes/api/admin/organization/$id'
import { Route as ApiAdminNavitemVisibilityRouteImport } from './routes/api/admin/navitem/visibility'
import { Route as ApiAdminNavitemOrderRouteImport } from './routes/api/admin/navitem/order'
import { Route as ApiAdminNavitemIdRouteImport } from './routes/api/admin/navitem/$id'
import { Route as ApiAdminNavgroupVisibilityRouteImport } from './routes/api/admin/navgroup/visibility'
import { Route as ApiAdminNavgroupOrderRouteImport } from './routes/api/admin/navgroup/order'
import { Route as ApiAdminNavgroupIdRouteImport } from './routes/api/admin/navgroup/$id'
import { Route as ApiAdminMemberBatchRouteImport } from './routes/api/admin/member/batch'
import { Route as ApiAdminMemberIdRouteImport } from './routes/api/admin/member/$id'
import { Route as ApiAdminInvitationBatchRouteImport } from './routes/api/admin/invitation/batch'
import { Route as ApiAdminInvitationIdRouteImport } from './routes/api/admin/invitation/$id'
import { Route as AdminOrganizationMemberCreateRouteImport } from './routes/admin/organization/member/create'
import { Route as AdminOrganizationMemberIdRouteImport } from './routes/admin/organization/member/$id'
import { Route as AuthenticatedDemoSettingsNotificationsRouteImport } from './routes/_authenticated/demo/settings/notifications'
import { Route as AuthenticatedDemoSettingsDisplayRouteImport } from './routes/_authenticated/demo/settings/display'
import { Route as AuthenticatedDemoSettingsAppearanceRouteImport } from './routes/_authenticated/demo/settings/appearance'
import { Route as AuthenticatedDemoSettingsAccountRouteImport } from './routes/_authenticated/demo/settings/account'
import { Route as ApiAdminRoleIdNavGroupsRouteImport } from './routes/api/admin/role/$id.nav-groups'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRouteRoute = QuestionBankRouteRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankIndexRoute = QuestionBankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const QuestionBankTagsRoute = QuestionBankTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankQuestionsRoute = QuestionBankQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankPracticeRoute = QuestionBankPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankImportExportRoute =
  QuestionBankImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => QuestionBankRouteRoute,
  } as any)
const QuestionBankCategoriesRoute = QuestionBankCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankAnalyticsRoute = QuestionBankAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserrolenavgroupRoute = AdminUserrolenavgroupRouteImport.update({
  id: '/userrolenavgroup',
  path: '/userrolenavgroup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTranslationRoute = AdminTranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSessionRoute = AdminSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolenavgroupRoute = AdminRolenavgroupRouteImport.update({
  id: '/rolenavgroup',
  path: '/rolenavgroup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavitemRoute = AdminNavitemRouteImport.update({
  id: '/navitem',
  path: '/navitem',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavgroupRoute = AdminNavgroupRouteImport.update({
  id: '/navgroup',
  path: '/navgroup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationIndexRoute = AdminOrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiI18nLngRoute = ApiI18nLngRouteImport.update({
  id: '/api/i18n/$lng',
  path: '/api/i18n/$lng',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationMemberRoute = AdminOrganizationMemberRouteImport.update({
  id: '/organization/member',
  path: '/organization/member',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationInvitationRoute =
  AdminOrganizationInvitationRouteImport.update({
    id: '/organization/invitation',
    path: '/organization/invitation',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrganizationCreateRoute = AdminOrganizationCreateRouteImport.update({
  id: '/organization/create',
  path: '/organization/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationIdRoute = AdminOrganizationIdRouteImport.update({
  id: '/organization/$id',
  path: '/organization/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsRouteRoute =
  AuthenticatedDemoSettingsRouteRouteImport.update({
    id: '/demo/settings',
    path: '/demo/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiQuestionBankTagsIndexRoute =
  ApiQuestionBankTagsIndexRouteImport.update({
    id: '/api/question-bank/tags/',
    path: '/api/question-bank/tags/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankQuestionsIndexRoute =
  ApiQuestionBankQuestionsIndexRouteImport.update({
    id: '/api/question-bank/questions/',
    path: '/api/question-bank/questions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankCategoriesIndexRoute =
  ApiQuestionBankCategoriesIndexRouteImport.update({
    id: '/api/question-bank/categories/',
    path: '/api/question-bank/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDemoTasksIndexRoute = ApiDemoTasksIndexRouteImport.update({
  id: '/api/demo/tasks/',
  path: '/api/demo/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserIndexRoute = ApiAdminUserIndexRouteImport.update({
  id: '/api/admin/user/',
  path: '/api/admin/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTranslationIndexRoute =
  ApiAdminTranslationIndexRouteImport.update({
    id: '/api/admin/translation/',
    path: '/api/admin/translation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSessionIndexRoute = ApiAdminSessionIndexRouteImport.update({
  id: '/api/admin/session/',
  path: '/api/admin/session/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoleIndexRoute = ApiAdminRoleIndexRouteImport.update({
  id: '/api/admin/role/',
  path: '/api/admin/role/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrganizationIndexRoute =
  ApiAdminOrganizationIndexRouteImport.update({
    id: '/api/admin/organization/',
    path: '/api/admin/organization/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminNavitemIndexRoute = ApiAdminNavitemIndexRouteImport.update({
  id: '/api/admin/navitem/',
  path: '/api/admin/navitem/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNavgroupIndexRoute = ApiAdminNavgroupIndexRouteImport.update({
  id: '/api/admin/navgroup/',
  path: '/api/admin/navgroup/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMemberIndexRoute = ApiAdminMemberIndexRouteImport.update({
  id: '/api/admin/member/',
  path: '/api/admin/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogIndexRoute = ApiAdminLogIndexRouteImport.update({
  id: '/api/admin/log/',
  path: '/api/admin/log/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitationIndexRoute = ApiAdminInvitationIndexRouteImport.update({
  id: '/api/admin/invitation/',
  path: '/api/admin/invitation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoUsersIndexRoute =
  AuthenticatedDemoUsersIndexRouteImport.update({
    id: '/demo/users/',
    path: '/demo/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoTasksIndexRoute =
  AuthenticatedDemoTasksIndexRouteImport.update({
    id: '/demo/tasks/',
    path: '/demo/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoSettingsIndexRoute =
  AuthenticatedDemoSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoChatsIndexRoute =
  AuthenticatedDemoChatsIndexRouteImport.update({
    id: '/demo/chats/',
    path: '/demo/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoAppsIndexRoute =
  AuthenticatedDemoAppsIndexRouteImport.update({
    id: '/demo/apps/',
    path: '/demo/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiQuestionBankTagsIdRoute = ApiQuestionBankTagsIdRouteImport.update({
  id: '/api/question-bank/tags/$id',
  path: '/api/question-bank/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionBankQuestionsIdRoute =
  ApiQuestionBankQuestionsIdRouteImport.update({
    id: '/api/question-bank/questions/$id',
    path: '/api/question-bank/questions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankCategoriesIdRoute =
  ApiQuestionBankCategoriesIdRouteImport.update({
    id: '/api/question-bank/categories/$id',
    path: '/api/question-bank/categories/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUserBulkDeleteRoute = ApiAdminUserBulkDeleteRouteImport.update({
  id: '/api/admin/user/bulk-delete',
  path: '/api/admin/user/bulk-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserBulkBanRoute = ApiAdminUserBulkBanRouteImport.update({
  id: '/api/admin/user/bulk-ban',
  path: '/api/admin/user/bulk-ban',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUserIdRoute = ApiAdminUserIdRouteImport.update({
  id: '/api/admin/user/$id',
  path: '/api/admin/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTranslationImportRoute =
  ApiAdminTranslationImportRouteImport.update({
    id: '/api/admin/translation/import',
    path: '/api/admin/translation/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTranslationExportRoute =
  ApiAdminTranslationExportRouteImport.update({
    id: '/api/admin/translation/export',
    path: '/api/admin/translation/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTranslationIdRoute = ApiAdminTranslationIdRouteImport.update({
  id: '/api/admin/translation/$id',
  path: '/api/admin/translation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionIdRoute = ApiAdminSessionIdRouteImport.update({
  id: '/api/admin/session/$id',
  path: '/api/admin/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoleIdRoute = ApiAdminRoleIdRouteImport.update({
  id: '/api/admin/role/$id',
  path: '/api/admin/role/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrganizationBatchRoute =
  ApiAdminOrganizationBatchRouteImport.update({
    id: '/api/admin/organization/batch',
    path: '/api/admin/organization/batch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOrganizationIdRoute = ApiAdminOrganizationIdRouteImport.update({
  id: '/api/admin/organization/$id',
  path: '/api/admin/organization/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNavitemVisibilityRoute =
  ApiAdminNavitemVisibilityRouteImport.update({
    id: '/api/admin/navitem/visibility',
    path: '/api/admin/navitem/visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminNavitemOrderRoute = ApiAdminNavitemOrderRouteImport.update({
  id: '/api/admin/navitem/order',
  path: '/api/admin/navitem/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNavitemIdRoute = ApiAdminNavitemIdRouteImport.update({
  id: '/api/admin/navitem/$id',
  path: '/api/admin/navitem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNavgroupVisibilityRoute =
  ApiAdminNavgroupVisibilityRouteImport.update({
    id: '/api/admin/navgroup/visibility',
    path: '/api/admin/navgroup/visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminNavgroupOrderRoute = ApiAdminNavgroupOrderRouteImport.update({
  id: '/api/admin/navgroup/order',
  path: '/api/admin/navgroup/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNavgroupIdRoute = ApiAdminNavgroupIdRouteImport.update({
  id: '/api/admin/navgroup/$id',
  path: '/api/admin/navgroup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMemberBatchRoute = ApiAdminMemberBatchRouteImport.update({
  id: '/api/admin/member/batch',
  path: '/api/admin/member/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMemberIdRoute = ApiAdminMemberIdRouteImport.update({
  id: '/api/admin/member/$id',
  path: '/api/admin/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitationBatchRoute = ApiAdminInvitationBatchRouteImport.update({
  id: '/api/admin/invitation/batch',
  path: '/api/admin/invitation/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvitationIdRoute = ApiAdminInvitationIdRouteImport.update({
  id: '/api/admin/invitation/$id',
  path: '/api/admin/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationMemberCreateRoute =
  AdminOrganizationMemberCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AdminOrganizationMemberRoute,
  } as any)
const AdminOrganizationMemberIdRoute =
  AdminOrganizationMemberIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminOrganizationMemberRoute,
  } as any)
const AuthenticatedDemoSettingsNotificationsRoute =
  AuthenticatedDemoSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsDisplayRoute =
  AuthenticatedDemoSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAppearanceRoute =
  AuthenticatedDemoSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAccountRoute =
  AuthenticatedDemoSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const ApiAdminRoleIdNavGroupsRoute = ApiAdminRoleIdNavGroupsRouteImport.update({
  id: '/nav-groups',
  path: '/nav-groups',
  getParentRoute: () => ApiAdminRoleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/question-bank': typeof QuestionBankRouteRouteWithChildren
  '/studio': typeof StudioRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/navgroup': typeof AdminNavgroupRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/navitem': typeof AdminNavitemRoute
  '/admin/rolenavgroup': typeof AdminRolenavgroupRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/userrolenavgroup': typeof AdminUserrolenavgroupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/question-bank/': typeof QuestionBankIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/admin/organization/$id': typeof AdminOrganizationIdRoute
  '/admin/organization/create': typeof AdminOrganizationCreateRoute
  '/admin/organization/invitation': typeof AdminOrganizationInvitationRoute
  '/admin/organization/member': typeof AdminOrganizationMemberRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/admin/organization': typeof AdminOrganizationIndexRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/admin/organization/member/$id': typeof AdminOrganizationMemberIdRoute
  '/admin/organization/member/create': typeof AdminOrganizationMemberCreateRoute
  '/api/admin/invitation/$id': typeof ApiAdminInvitationIdRoute
  '/api/admin/invitation/batch': typeof ApiAdminInvitationBatchRoute
  '/api/admin/member/$id': typeof ApiAdminMemberIdRoute
  '/api/admin/member/batch': typeof ApiAdminMemberBatchRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityRoute
  '/api/admin/organization/$id': typeof ApiAdminOrganizationIdRoute
  '/api/admin/organization/batch': typeof ApiAdminOrganizationBatchRoute
  '/api/admin/role/$id': typeof ApiAdminRoleIdRouteWithChildren
  '/api/admin/session/$id': typeof ApiAdminSessionIdRoute
  '/api/admin/translation/$id': typeof ApiAdminTranslationIdRoute
  '/api/admin/translation/export': typeof ApiAdminTranslationExportRoute
  '/api/admin/translation/import': typeof ApiAdminTranslationImportRoute
  '/api/admin/user/$id': typeof ApiAdminUserIdRoute
  '/api/admin/user/bulk-ban': typeof ApiAdminUserBulkBanRoute
  '/api/admin/user/bulk-delete': typeof ApiAdminUserBulkDeleteRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/demo/apps': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users': typeof AuthenticatedDemoUsersIndexRoute
  '/api/admin/invitation': typeof ApiAdminInvitationIndexRoute
  '/api/admin/log': typeof ApiAdminLogIndexRoute
  '/api/admin/member': typeof ApiAdminMemberIndexRoute
  '/api/admin/navgroup': typeof ApiAdminNavgroupIndexRoute
  '/api/admin/navitem': typeof ApiAdminNavitemIndexRoute
  '/api/admin/organization': typeof ApiAdminOrganizationIndexRoute
  '/api/admin/role': typeof ApiAdminRoleIndexRoute
  '/api/admin/session': typeof ApiAdminSessionIndexRoute
  '/api/admin/translation': typeof ApiAdminTranslationIndexRoute
  '/api/admin/user': typeof ApiAdminUserIndexRoute
  '/api/demo/tasks': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags': typeof ApiQuestionBankTagsIndexRoute
  '/api/admin/role/$id/nav-groups': typeof ApiAdminRoleIdNavGroupsRoute
}
export interface FileRoutesByTo {
  '/studio': typeof StudioRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/navgroup': typeof AdminNavgroupRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/navitem': typeof AdminNavitemRoute
  '/admin/rolenavgroup': typeof AdminRolenavgroupRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/userrolenavgroup': typeof AdminUserrolenavgroupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/': typeof publicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/question-bank': typeof QuestionBankIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/admin/organization/$id': typeof AdminOrganizationIdRoute
  '/admin/organization/create': typeof AdminOrganizationCreateRoute
  '/admin/organization/invitation': typeof AdminOrganizationInvitationRoute
  '/admin/organization/member': typeof AdminOrganizationMemberRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/admin/organization': typeof AdminOrganizationIndexRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/admin/organization/member/$id': typeof AdminOrganizationMemberIdRoute
  '/admin/organization/member/create': typeof AdminOrganizationMemberCreateRoute
  '/api/admin/invitation/$id': typeof ApiAdminInvitationIdRoute
  '/api/admin/invitation/batch': typeof ApiAdminInvitationBatchRoute
  '/api/admin/member/$id': typeof ApiAdminMemberIdRoute
  '/api/admin/member/batch': typeof ApiAdminMemberBatchRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityRoute
  '/api/admin/organization/$id': typeof ApiAdminOrganizationIdRoute
  '/api/admin/organization/batch': typeof ApiAdminOrganizationBatchRoute
  '/api/admin/role/$id': typeof ApiAdminRoleIdRouteWithChildren
  '/api/admin/session/$id': typeof ApiAdminSessionIdRoute
  '/api/admin/translation/$id': typeof ApiAdminTranslationIdRoute
  '/api/admin/translation/export': typeof ApiAdminTranslationExportRoute
  '/api/admin/translation/import': typeof ApiAdminTranslationImportRoute
  '/api/admin/user/$id': typeof ApiAdminUserIdRoute
  '/api/admin/user/bulk-ban': typeof ApiAdminUserBulkBanRoute
  '/api/admin/user/bulk-delete': typeof ApiAdminUserBulkDeleteRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/demo/apps': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users': typeof AuthenticatedDemoUsersIndexRoute
  '/api/admin/invitation': typeof ApiAdminInvitationIndexRoute
  '/api/admin/log': typeof ApiAdminLogIndexRoute
  '/api/admin/member': typeof ApiAdminMemberIndexRoute
  '/api/admin/navgroup': typeof ApiAdminNavgroupIndexRoute
  '/api/admin/navitem': typeof ApiAdminNavitemIndexRoute
  '/api/admin/organization': typeof ApiAdminOrganizationIndexRoute
  '/api/admin/role': typeof ApiAdminRoleIndexRoute
  '/api/admin/session': typeof ApiAdminSessionIndexRoute
  '/api/admin/translation': typeof ApiAdminTranslationIndexRoute
  '/api/admin/user': typeof ApiAdminUserIndexRoute
  '/api/demo/tasks': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags': typeof ApiQuestionBankTagsIndexRoute
  '/api/admin/role/$id/nav-groups': typeof ApiAdminRoleIdNavGroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/question-bank': typeof QuestionBankRouteRouteWithChildren
  '/studio': typeof StudioRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(public)/about': typeof publicAboutRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/navgroup': typeof AdminNavgroupRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/navitem': typeof AdminNavitemRoute
  '/admin/rolenavgroup': typeof AdminRolenavgroupRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/translation': typeof AdminTranslationRoute
  '/admin/userrolenavgroup': typeof AdminUserrolenavgroupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/(public)/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/question-bank/': typeof QuestionBankIndexRoute
  '/_authenticated/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/admin/organization/$id': typeof AdminOrganizationIdRoute
  '/admin/organization/create': typeof AdminOrganizationCreateRoute
  '/admin/organization/invitation': typeof AdminOrganizationInvitationRoute
  '/admin/organization/member': typeof AdminOrganizationMemberRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/admin/organization/': typeof AdminOrganizationIndexRoute
  '/_authenticated/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/_authenticated/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/_authenticated/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/_authenticated/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/admin/organization/member/$id': typeof AdminOrganizationMemberIdRoute
  '/admin/organization/member/create': typeof AdminOrganizationMemberCreateRoute
  '/api/admin/invitation/$id': typeof ApiAdminInvitationIdRoute
  '/api/admin/invitation/batch': typeof ApiAdminInvitationBatchRoute
  '/api/admin/member/$id': typeof ApiAdminMemberIdRoute
  '/api/admin/member/batch': typeof ApiAdminMemberBatchRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityRoute
  '/api/admin/organization/$id': typeof ApiAdminOrganizationIdRoute
  '/api/admin/organization/batch': typeof ApiAdminOrganizationBatchRoute
  '/api/admin/role/$id': typeof ApiAdminRoleIdRouteWithChildren
  '/api/admin/session/$id': typeof ApiAdminSessionIdRoute
  '/api/admin/translation/$id': typeof ApiAdminTranslationIdRoute
  '/api/admin/translation/export': typeof ApiAdminTranslationExportRoute
  '/api/admin/translation/import': typeof ApiAdminTranslationImportRoute
  '/api/admin/user/$id': typeof ApiAdminUserIdRoute
  '/api/admin/user/bulk-ban': typeof ApiAdminUserBulkBanRoute
  '/api/admin/user/bulk-delete': typeof ApiAdminUserBulkDeleteRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/_authenticated/demo/apps/': typeof AuthenticatedDemoAppsIndexRoute
  '/_authenticated/demo/chats/': typeof AuthenticatedDemoChatsIndexRoute
  '/_authenticated/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/_authenticated/demo/tasks/': typeof AuthenticatedDemoTasksIndexRoute
  '/_authenticated/demo/users/': typeof AuthenticatedDemoUsersIndexRoute
  '/api/admin/invitation/': typeof ApiAdminInvitationIndexRoute
  '/api/admin/log/': typeof ApiAdminLogIndexRoute
  '/api/admin/member/': typeof ApiAdminMemberIndexRoute
  '/api/admin/navgroup/': typeof ApiAdminNavgroupIndexRoute
  '/api/admin/navitem/': typeof ApiAdminNavitemIndexRoute
  '/api/admin/organization/': typeof ApiAdminOrganizationIndexRoute
  '/api/admin/role/': typeof ApiAdminRoleIndexRoute
  '/api/admin/session/': typeof ApiAdminSessionIndexRoute
  '/api/admin/translation/': typeof ApiAdminTranslationIndexRoute
  '/api/admin/user/': typeof ApiAdminUserIndexRoute
  '/api/demo/tasks/': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories/': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions/': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags/': typeof ApiQuestionBankTagsIndexRoute
  '/api/admin/role/$id/nav-groups': typeof ApiAdminRoleIdNavGroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/question-bank'
    | '/studio'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/admin/account'
    | '/admin/log'
    | '/admin/navgroup'
    | '/admin/navigation'
    | '/admin/navitem'
    | '/admin/rolenavgroup'
    | '/admin/roles'
    | '/admin/session'
    | '/admin/translation'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/'
    | '/admin/'
    | '/question-bank/'
    | '/demo/settings'
    | '/errors/$error'
    | '/admin/organization/$id'
    | '/admin/organization/create'
    | '/admin/organization/invitation'
    | '/admin/organization/member'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/help-center'
    | '/sessions'
    | '/admin/organization'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/admin/organization/member/$id'
    | '/admin/organization/member/create'
    | '/api/admin/invitation/$id'
    | '/api/admin/invitation/batch'
    | '/api/admin/member/$id'
    | '/api/admin/member/batch'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/organization/$id'
    | '/api/admin/organization/batch'
    | '/api/admin/role/$id'
    | '/api/admin/session/$id'
    | '/api/admin/translation/$id'
    | '/api/admin/translation/export'
    | '/api/admin/translation/import'
    | '/api/admin/user/$id'
    | '/api/admin/user/bulk-ban'
    | '/api/admin/user/bulk-delete'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/settings/'
    | '/demo/tasks'
    | '/demo/users'
    | '/api/admin/invitation'
    | '/api/admin/log'
    | '/api/admin/member'
    | '/api/admin/navgroup'
    | '/api/admin/navitem'
    | '/api/admin/organization'
    | '/api/admin/role'
    | '/api/admin/session'
    | '/api/admin/translation'
    | '/api/admin/user'
    | '/api/demo/tasks'
    | '/api/question-bank/categories'
    | '/api/question-bank/questions'
    | '/api/question-bank/tags'
    | '/api/admin/role/$id/nav-groups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/admin/account'
    | '/admin/log'
    | '/admin/navgroup'
    | '/admin/navigation'
    | '/admin/navitem'
    | '/admin/rolenavgroup'
    | '/admin/roles'
    | '/admin/session'
    | '/admin/translation'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/'
    | '/admin'
    | '/question-bank'
    | '/errors/$error'
    | '/admin/organization/$id'
    | '/admin/organization/create'
    | '/admin/organization/invitation'
    | '/admin/organization/member'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/help-center'
    | '/sessions'
    | '/admin/organization'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/admin/organization/member/$id'
    | '/admin/organization/member/create'
    | '/api/admin/invitation/$id'
    | '/api/admin/invitation/batch'
    | '/api/admin/member/$id'
    | '/api/admin/member/batch'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/organization/$id'
    | '/api/admin/organization/batch'
    | '/api/admin/role/$id'
    | '/api/admin/session/$id'
    | '/api/admin/translation/$id'
    | '/api/admin/translation/export'
    | '/api/admin/translation/import'
    | '/api/admin/user/$id'
    | '/api/admin/user/bulk-ban'
    | '/api/admin/user/bulk-delete'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/settings'
    | '/demo/tasks'
    | '/demo/users'
    | '/api/admin/invitation'
    | '/api/admin/log'
    | '/api/admin/member'
    | '/api/admin/navgroup'
    | '/api/admin/navitem'
    | '/api/admin/organization'
    | '/api/admin/role'
    | '/api/admin/session'
    | '/api/admin/translation'
    | '/api/admin/user'
    | '/api/demo/tasks'
    | '/api/question-bank/categories'
    | '/api/question-bank/questions'
    | '/api/question-bank/tags'
    | '/api/admin/role/$id/nav-groups'
  id:
    | '__root__'
    | '/(public)'
    | '/_authenticated'
    | '/admin'
    | '/question-bank'
    | '/studio'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(public)/about'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/_authenticated/dashboard'
    | '/admin/account'
    | '/admin/log'
    | '/admin/navgroup'
    | '/admin/navigation'
    | '/admin/navitem'
    | '/admin/rolenavgroup'
    | '/admin/roles'
    | '/admin/session'
    | '/admin/translation'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/(public)/'
    | '/admin/'
    | '/question-bank/'
    | '/_authenticated/demo/settings'
    | '/_authenticated/errors/$error'
    | '/admin/organization/$id'
    | '/admin/organization/create'
    | '/admin/organization/invitation'
    | '/admin/organization/member'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/_authenticated/help-center/'
    | '/_authenticated/sessions/'
    | '/admin/organization/'
    | '/_authenticated/demo/settings/account'
    | '/_authenticated/demo/settings/appearance'
    | '/_authenticated/demo/settings/display'
    | '/_authenticated/demo/settings/notifications'
    | '/admin/organization/member/$id'
    | '/admin/organization/member/create'
    | '/api/admin/invitation/$id'
    | '/api/admin/invitation/batch'
    | '/api/admin/member/$id'
    | '/api/admin/member/batch'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/organization/$id'
    | '/api/admin/organization/batch'
    | '/api/admin/role/$id'
    | '/api/admin/session/$id'
    | '/api/admin/translation/$id'
    | '/api/admin/translation/export'
    | '/api/admin/translation/import'
    | '/api/admin/user/$id'
    | '/api/admin/user/bulk-ban'
    | '/api/admin/user/bulk-delete'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/_authenticated/demo/apps/'
    | '/_authenticated/demo/chats/'
    | '/_authenticated/demo/settings/'
    | '/_authenticated/demo/tasks/'
    | '/_authenticated/demo/users/'
    | '/api/admin/invitation/'
    | '/api/admin/log/'
    | '/api/admin/member/'
    | '/api/admin/navgroup/'
    | '/api/admin/navitem/'
    | '/api/admin/organization/'
    | '/api/admin/role/'
    | '/api/admin/session/'
    | '/api/admin/translation/'
    | '/api/admin/user/'
    | '/api/demo/tasks/'
    | '/api/question-bank/categories/'
    | '/api/question-bank/questions/'
    | '/api/question-bank/tags/'
    | '/api/admin/role/$id/nav-groups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  QuestionBankRouteRoute: typeof QuestionBankRouteRouteWithChildren
  StudioRoute: typeof StudioRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiI18nLngRoute: typeof ApiI18nLngRoute
  ApiAdminInvitationIdRoute: typeof ApiAdminInvitationIdRoute
  ApiAdminInvitationBatchRoute: typeof ApiAdminInvitationBatchRoute
  ApiAdminMemberIdRoute: typeof ApiAdminMemberIdRoute
  ApiAdminMemberBatchRoute: typeof ApiAdminMemberBatchRoute
  ApiAdminNavgroupIdRoute: typeof ApiAdminNavgroupIdRoute
  ApiAdminNavgroupOrderRoute: typeof ApiAdminNavgroupOrderRoute
  ApiAdminNavgroupVisibilityRoute: typeof ApiAdminNavgroupVisibilityRoute
  ApiAdminNavitemIdRoute: typeof ApiAdminNavitemIdRoute
  ApiAdminNavitemOrderRoute: typeof ApiAdminNavitemOrderRoute
  ApiAdminNavitemVisibilityRoute: typeof ApiAdminNavitemVisibilityRoute
  ApiAdminOrganizationIdRoute: typeof ApiAdminOrganizationIdRoute
  ApiAdminOrganizationBatchRoute: typeof ApiAdminOrganizationBatchRoute
  ApiAdminRoleIdRoute: typeof ApiAdminRoleIdRouteWithChildren
  ApiAdminSessionIdRoute: typeof ApiAdminSessionIdRoute
  ApiAdminTranslationIdRoute: typeof ApiAdminTranslationIdRoute
  ApiAdminTranslationExportRoute: typeof ApiAdminTranslationExportRoute
  ApiAdminTranslationImportRoute: typeof ApiAdminTranslationImportRoute
  ApiAdminUserIdRoute: typeof ApiAdminUserIdRoute
  ApiAdminUserBulkBanRoute: typeof ApiAdminUserBulkBanRoute
  ApiAdminUserBulkDeleteRoute: typeof ApiAdminUserBulkDeleteRoute
  ApiQuestionBankCategoriesIdRoute: typeof ApiQuestionBankCategoriesIdRoute
  ApiQuestionBankQuestionsIdRoute: typeof ApiQuestionBankQuestionsIdRoute
  ApiQuestionBankTagsIdRoute: typeof ApiQuestionBankTagsIdRoute
  ApiAdminInvitationIndexRoute: typeof ApiAdminInvitationIndexRoute
  ApiAdminLogIndexRoute: typeof ApiAdminLogIndexRoute
  ApiAdminMemberIndexRoute: typeof ApiAdminMemberIndexRoute
  ApiAdminNavgroupIndexRoute: typeof ApiAdminNavgroupIndexRoute
  ApiAdminNavitemIndexRoute: typeof ApiAdminNavitemIndexRoute
  ApiAdminOrganizationIndexRoute: typeof ApiAdminOrganizationIndexRoute
  ApiAdminRoleIndexRoute: typeof ApiAdminRoleIndexRoute
  ApiAdminSessionIndexRoute: typeof ApiAdminSessionIndexRoute
  ApiAdminTranslationIndexRoute: typeof ApiAdminTranslationIndexRoute
  ApiAdminUserIndexRoute: typeof ApiAdminUserIndexRoute
  ApiDemoTasksIndexRoute: typeof ApiDemoTasksIndexRoute
  ApiQuestionBankCategoriesIndexRoute: typeof ApiQuestionBankCategoriesIndexRoute
  ApiQuestionBankQuestionsIndexRoute: typeof ApiQuestionBankQuestionsIndexRoute
  ApiQuestionBankTagsIndexRoute: typeof ApiQuestionBankTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank/': {
      id: '/question-bank/'
      path: '/'
      fullPath: '/question-bank/'
      preLoaderRoute: typeof QuestionBankIndexRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/question-bank/tags': {
      id: '/question-bank/tags'
      path: '/tags'
      fullPath: '/question-bank/tags'
      preLoaderRoute: typeof QuestionBankTagsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/questions': {
      id: '/question-bank/questions'
      path: '/questions'
      fullPath: '/question-bank/questions'
      preLoaderRoute: typeof QuestionBankQuestionsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/practice': {
      id: '/question-bank/practice'
      path: '/practice'
      fullPath: '/question-bank/practice'
      preLoaderRoute: typeof QuestionBankPracticeRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/import-export': {
      id: '/question-bank/import-export'
      path: '/import-export'
      fullPath: '/question-bank/import-export'
      preLoaderRoute: typeof QuestionBankImportExportRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/categories': {
      id: '/question-bank/categories'
      path: '/categories'
      fullPath: '/question-bank/categories'
      preLoaderRoute: typeof QuestionBankCategoriesRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/analytics': {
      id: '/question-bank/analytics'
      path: '/analytics'
      fullPath: '/question-bank/analytics'
      preLoaderRoute: typeof QuestionBankAnalyticsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/userrolenavgroup': {
      id: '/admin/userrolenavgroup'
      path: '/userrolenavgroup'
      fullPath: '/admin/userrolenavgroup'
      preLoaderRoute: typeof AdminUserrolenavgroupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/translation': {
      id: '/admin/translation'
      path: '/translation'
      fullPath: '/admin/translation'
      preLoaderRoute: typeof AdminTranslationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/session': {
      id: '/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AdminSessionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rolenavgroup': {
      id: '/admin/rolenavgroup'
      path: '/rolenavgroup'
      fullPath: '/admin/rolenavgroup'
      preLoaderRoute: typeof AdminRolenavgroupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/navitem': {
      id: '/admin/navitem'
      path: '/navitem'
      fullPath: '/admin/navitem'
      preLoaderRoute: typeof AdminNavitemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/navgroup': {
      id: '/admin/navgroup'
      path: '/navgroup'
      fullPath: '/admin/navgroup'
      preLoaderRoute: typeof AdminNavgroupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/': {
      id: '/admin/organization/'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/i18n/$lng': {
      id: '/api/i18n/$lng'
      path: '/api/i18n/$lng'
      fullPath: '/api/i18n/$lng'
      preLoaderRoute: typeof ApiI18nLngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/member': {
      id: '/admin/organization/member'
      path: '/organization/member'
      fullPath: '/admin/organization/member'
      preLoaderRoute: typeof AdminOrganizationMemberRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization/invitation': {
      id: '/admin/organization/invitation'
      path: '/organization/invitation'
      fullPath: '/admin/organization/invitation'
      preLoaderRoute: typeof AdminOrganizationInvitationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization/create': {
      id: '/admin/organization/create'
      path: '/organization/create'
      fullPath: '/admin/organization/create'
      preLoaderRoute: typeof AdminOrganizationCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organization/$id': {
      id: '/admin/organization/$id'
      path: '/organization/$id'
      fullPath: '/admin/organization/$id'
      preLoaderRoute: typeof AdminOrganizationIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings': {
      id: '/_authenticated/demo/settings'
      path: '/demo/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof AuthenticatedDemoSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/question-bank/tags/': {
      id: '/api/question-bank/tags/'
      path: '/api/question-bank/tags'
      fullPath: '/api/question-bank/tags'
      preLoaderRoute: typeof ApiQuestionBankTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/questions/': {
      id: '/api/question-bank/questions/'
      path: '/api/question-bank/questions'
      fullPath: '/api/question-bank/questions'
      preLoaderRoute: typeof ApiQuestionBankQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/categories/': {
      id: '/api/question-bank/categories/'
      path: '/api/question-bank/categories'
      fullPath: '/api/question-bank/categories'
      preLoaderRoute: typeof ApiQuestionBankCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/tasks/': {
      id: '/api/demo/tasks/'
      path: '/api/demo/tasks'
      fullPath: '/api/demo/tasks'
      preLoaderRoute: typeof ApiDemoTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user/': {
      id: '/api/admin/user/'
      path: '/api/admin/user'
      fullPath: '/api/admin/user'
      preLoaderRoute: typeof ApiAdminUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/translation/': {
      id: '/api/admin/translation/'
      path: '/api/admin/translation'
      fullPath: '/api/admin/translation'
      preLoaderRoute: typeof ApiAdminTranslationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session/': {
      id: '/api/admin/session/'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/role/': {
      id: '/api/admin/role/'
      path: '/api/admin/role'
      fullPath: '/api/admin/role'
      preLoaderRoute: typeof ApiAdminRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organization/': {
      id: '/api/admin/organization/'
      path: '/api/admin/organization'
      fullPath: '/api/admin/organization'
      preLoaderRoute: typeof ApiAdminOrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navitem/': {
      id: '/api/admin/navitem/'
      path: '/api/admin/navitem'
      fullPath: '/api/admin/navitem'
      preLoaderRoute: typeof ApiAdminNavitemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navgroup/': {
      id: '/api/admin/navgroup/'
      path: '/api/admin/navgroup'
      fullPath: '/api/admin/navgroup'
      preLoaderRoute: typeof ApiAdminNavgroupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/member/': {
      id: '/api/admin/member/'
      path: '/api/admin/member'
      fullPath: '/api/admin/member'
      preLoaderRoute: typeof ApiAdminMemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/log/': {
      id: '/api/admin/log/'
      path: '/api/admin/log'
      fullPath: '/api/admin/log'
      preLoaderRoute: typeof ApiAdminLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invitation/': {
      id: '/api/admin/invitation/'
      path: '/api/admin/invitation'
      fullPath: '/api/admin/invitation'
      preLoaderRoute: typeof ApiAdminInvitationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/users/': {
      id: '/_authenticated/demo/users/'
      path: '/demo/users'
      fullPath: '/demo/users'
      preLoaderRoute: typeof AuthenticatedDemoUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/tasks/': {
      id: '/_authenticated/demo/tasks/'
      path: '/demo/tasks'
      fullPath: '/demo/tasks'
      preLoaderRoute: typeof AuthenticatedDemoTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/settings/': {
      id: '/_authenticated/demo/settings/'
      path: '/'
      fullPath: '/demo/settings/'
      preLoaderRoute: typeof AuthenticatedDemoSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/chats/': {
      id: '/_authenticated/demo/chats/'
      path: '/demo/chats'
      fullPath: '/demo/chats'
      preLoaderRoute: typeof AuthenticatedDemoChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/apps/': {
      id: '/_authenticated/demo/apps/'
      path: '/demo/apps'
      fullPath: '/demo/apps'
      preLoaderRoute: typeof AuthenticatedDemoAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/question-bank/tags/$id': {
      id: '/api/question-bank/tags/$id'
      path: '/api/question-bank/tags/$id'
      fullPath: '/api/question-bank/tags/$id'
      preLoaderRoute: typeof ApiQuestionBankTagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/questions/$id': {
      id: '/api/question-bank/questions/$id'
      path: '/api/question-bank/questions/$id'
      fullPath: '/api/question-bank/questions/$id'
      preLoaderRoute: typeof ApiQuestionBankQuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/categories/$id': {
      id: '/api/question-bank/categories/$id'
      path: '/api/question-bank/categories/$id'
      fullPath: '/api/question-bank/categories/$id'
      preLoaderRoute: typeof ApiQuestionBankCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user/bulk-delete': {
      id: '/api/admin/user/bulk-delete'
      path: '/api/admin/user/bulk-delete'
      fullPath: '/api/admin/user/bulk-delete'
      preLoaderRoute: typeof ApiAdminUserBulkDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user/bulk-ban': {
      id: '/api/admin/user/bulk-ban'
      path: '/api/admin/user/bulk-ban'
      fullPath: '/api/admin/user/bulk-ban'
      preLoaderRoute: typeof ApiAdminUserBulkBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/user/$id': {
      id: '/api/admin/user/$id'
      path: '/api/admin/user/$id'
      fullPath: '/api/admin/user/$id'
      preLoaderRoute: typeof ApiAdminUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/translation/import': {
      id: '/api/admin/translation/import'
      path: '/api/admin/translation/import'
      fullPath: '/api/admin/translation/import'
      preLoaderRoute: typeof ApiAdminTranslationImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/translation/export': {
      id: '/api/admin/translation/export'
      path: '/api/admin/translation/export'
      fullPath: '/api/admin/translation/export'
      preLoaderRoute: typeof ApiAdminTranslationExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/translation/$id': {
      id: '/api/admin/translation/$id'
      path: '/api/admin/translation/$id'
      fullPath: '/api/admin/translation/$id'
      preLoaderRoute: typeof ApiAdminTranslationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session/$id': {
      id: '/api/admin/session/$id'
      path: '/api/admin/session/$id'
      fullPath: '/api/admin/session/$id'
      preLoaderRoute: typeof ApiAdminSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/role/$id': {
      id: '/api/admin/role/$id'
      path: '/api/admin/role/$id'
      fullPath: '/api/admin/role/$id'
      preLoaderRoute: typeof ApiAdminRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organization/batch': {
      id: '/api/admin/organization/batch'
      path: '/api/admin/organization/batch'
      fullPath: '/api/admin/organization/batch'
      preLoaderRoute: typeof ApiAdminOrganizationBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organization/$id': {
      id: '/api/admin/organization/$id'
      path: '/api/admin/organization/$id'
      fullPath: '/api/admin/organization/$id'
      preLoaderRoute: typeof ApiAdminOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navitem/visibility': {
      id: '/api/admin/navitem/visibility'
      path: '/api/admin/navitem/visibility'
      fullPath: '/api/admin/navitem/visibility'
      preLoaderRoute: typeof ApiAdminNavitemVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navitem/order': {
      id: '/api/admin/navitem/order'
      path: '/api/admin/navitem/order'
      fullPath: '/api/admin/navitem/order'
      preLoaderRoute: typeof ApiAdminNavitemOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navitem/$id': {
      id: '/api/admin/navitem/$id'
      path: '/api/admin/navitem/$id'
      fullPath: '/api/admin/navitem/$id'
      preLoaderRoute: typeof ApiAdminNavitemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navgroup/visibility': {
      id: '/api/admin/navgroup/visibility'
      path: '/api/admin/navgroup/visibility'
      fullPath: '/api/admin/navgroup/visibility'
      preLoaderRoute: typeof ApiAdminNavgroupVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navgroup/order': {
      id: '/api/admin/navgroup/order'
      path: '/api/admin/navgroup/order'
      fullPath: '/api/admin/navgroup/order'
      preLoaderRoute: typeof ApiAdminNavgroupOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/navgroup/$id': {
      id: '/api/admin/navgroup/$id'
      path: '/api/admin/navgroup/$id'
      fullPath: '/api/admin/navgroup/$id'
      preLoaderRoute: typeof ApiAdminNavgroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/member/batch': {
      id: '/api/admin/member/batch'
      path: '/api/admin/member/batch'
      fullPath: '/api/admin/member/batch'
      preLoaderRoute: typeof ApiAdminMemberBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/member/$id': {
      id: '/api/admin/member/$id'
      path: '/api/admin/member/$id'
      fullPath: '/api/admin/member/$id'
      preLoaderRoute: typeof ApiAdminMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invitation/batch': {
      id: '/api/admin/invitation/batch'
      path: '/api/admin/invitation/batch'
      fullPath: '/api/admin/invitation/batch'
      preLoaderRoute: typeof ApiAdminInvitationBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invitation/$id': {
      id: '/api/admin/invitation/$id'
      path: '/api/admin/invitation/$id'
      fullPath: '/api/admin/invitation/$id'
      preLoaderRoute: typeof ApiAdminInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/member/create': {
      id: '/admin/organization/member/create'
      path: '/create'
      fullPath: '/admin/organization/member/create'
      preLoaderRoute: typeof AdminOrganizationMemberCreateRouteImport
      parentRoute: typeof AdminOrganizationMemberRoute
    }
    '/admin/organization/member/$id': {
      id: '/admin/organization/member/$id'
      path: '/$id'
      fullPath: '/admin/organization/member/$id'
      preLoaderRoute: typeof AdminOrganizationMemberIdRouteImport
      parentRoute: typeof AdminOrganizationMemberRoute
    }
    '/_authenticated/demo/settings/notifications': {
      id: '/_authenticated/demo/settings/notifications'
      path: '/notifications'
      fullPath: '/demo/settings/notifications'
      preLoaderRoute: typeof AuthenticatedDemoSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/display': {
      id: '/_authenticated/demo/settings/display'
      path: '/display'
      fullPath: '/demo/settings/display'
      preLoaderRoute: typeof AuthenticatedDemoSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/appearance': {
      id: '/_authenticated/demo/settings/appearance'
      path: '/appearance'
      fullPath: '/demo/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/account': {
      id: '/_authenticated/demo/settings/account'
      path: '/account'
      fullPath: '/demo/settings/account'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/api/admin/role/$id/nav-groups': {
      id: '/api/admin/role/$id/nav-groups'
      path: '/nav-groups'
      fullPath: '/api/admin/role/$id/nav-groups'
      preLoaderRoute: typeof ApiAdminRoleIdNavGroupsRouteImport
      parentRoute: typeof ApiAdminRoleIdRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AuthenticatedDemoSettingsRouteRouteChildren {
  AuthenticatedDemoSettingsAccountRoute: typeof AuthenticatedDemoSettingsAccountRoute
  AuthenticatedDemoSettingsAppearanceRoute: typeof AuthenticatedDemoSettingsAppearanceRoute
  AuthenticatedDemoSettingsDisplayRoute: typeof AuthenticatedDemoSettingsDisplayRoute
  AuthenticatedDemoSettingsNotificationsRoute: typeof AuthenticatedDemoSettingsNotificationsRoute
  AuthenticatedDemoSettingsIndexRoute: typeof AuthenticatedDemoSettingsIndexRoute
}

const AuthenticatedDemoSettingsRouteRouteChildren: AuthenticatedDemoSettingsRouteRouteChildren =
  {
    AuthenticatedDemoSettingsAccountRoute:
      AuthenticatedDemoSettingsAccountRoute,
    AuthenticatedDemoSettingsAppearanceRoute:
      AuthenticatedDemoSettingsAppearanceRoute,
    AuthenticatedDemoSettingsDisplayRoute:
      AuthenticatedDemoSettingsDisplayRoute,
    AuthenticatedDemoSettingsNotificationsRoute:
      AuthenticatedDemoSettingsNotificationsRoute,
    AuthenticatedDemoSettingsIndexRoute: AuthenticatedDemoSettingsIndexRoute,
  }

const AuthenticatedDemoSettingsRouteRouteWithChildren =
  AuthenticatedDemoSettingsRouteRoute._addFileChildren(
    AuthenticatedDemoSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoSettingsRouteRoute: typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedDemoAppsIndexRoute: typeof AuthenticatedDemoAppsIndexRoute
  AuthenticatedDemoChatsIndexRoute: typeof AuthenticatedDemoChatsIndexRoute
  AuthenticatedDemoTasksIndexRoute: typeof AuthenticatedDemoTasksIndexRoute
  AuthenticatedDemoUsersIndexRoute: typeof AuthenticatedDemoUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoSettingsRouteRoute:
    AuthenticatedDemoSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedDemoAppsIndexRoute: AuthenticatedDemoAppsIndexRoute,
  AuthenticatedDemoChatsIndexRoute: AuthenticatedDemoChatsIndexRoute,
  AuthenticatedDemoTasksIndexRoute: AuthenticatedDemoTasksIndexRoute,
  AuthenticatedDemoUsersIndexRoute: AuthenticatedDemoUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminOrganizationMemberRouteChildren {
  AdminOrganizationMemberIdRoute: typeof AdminOrganizationMemberIdRoute
  AdminOrganizationMemberCreateRoute: typeof AdminOrganizationMemberCreateRoute
}

const AdminOrganizationMemberRouteChildren: AdminOrganizationMemberRouteChildren =
  {
    AdminOrganizationMemberIdRoute: AdminOrganizationMemberIdRoute,
    AdminOrganizationMemberCreateRoute: AdminOrganizationMemberCreateRoute,
  }

const AdminOrganizationMemberRouteWithChildren =
  AdminOrganizationMemberRoute._addFileChildren(
    AdminOrganizationMemberRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminNavgroupRoute: typeof AdminNavgroupRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNavitemRoute: typeof AdminNavitemRoute
  AdminRolenavgroupRoute: typeof AdminRolenavgroupRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSessionRoute: typeof AdminSessionRoute
  AdminTranslationRoute: typeof AdminTranslationRoute
  AdminUserrolenavgroupRoute: typeof AdminUserrolenavgroupRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationIdRoute: typeof AdminOrganizationIdRoute
  AdminOrganizationCreateRoute: typeof AdminOrganizationCreateRoute
  AdminOrganizationInvitationRoute: typeof AdminOrganizationInvitationRoute
  AdminOrganizationMemberRoute: typeof AdminOrganizationMemberRouteWithChildren
  AdminOrganizationIndexRoute: typeof AdminOrganizationIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminLogRoute: AdminLogRoute,
  AdminNavgroupRoute: AdminNavgroupRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNavitemRoute: AdminNavitemRoute,
  AdminRolenavgroupRoute: AdminRolenavgroupRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSessionRoute: AdminSessionRoute,
  AdminTranslationRoute: AdminTranslationRoute,
  AdminUserrolenavgroupRoute: AdminUserrolenavgroupRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationIdRoute: AdminOrganizationIdRoute,
  AdminOrganizationCreateRoute: AdminOrganizationCreateRoute,
  AdminOrganizationInvitationRoute: AdminOrganizationInvitationRoute,
  AdminOrganizationMemberRoute: AdminOrganizationMemberRouteWithChildren,
  AdminOrganizationIndexRoute: AdminOrganizationIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface QuestionBankRouteRouteChildren {
  QuestionBankAnalyticsRoute: typeof QuestionBankAnalyticsRoute
  QuestionBankCategoriesRoute: typeof QuestionBankCategoriesRoute
  QuestionBankImportExportRoute: typeof QuestionBankImportExportRoute
  QuestionBankPracticeRoute: typeof QuestionBankPracticeRoute
  QuestionBankQuestionsRoute: typeof QuestionBankQuestionsRoute
  QuestionBankTagsRoute: typeof QuestionBankTagsRoute
  QuestionBankIndexRoute: typeof QuestionBankIndexRoute
}

const QuestionBankRouteRouteChildren: QuestionBankRouteRouteChildren = {
  QuestionBankAnalyticsRoute: QuestionBankAnalyticsRoute,
  QuestionBankCategoriesRoute: QuestionBankCategoriesRoute,
  QuestionBankImportExportRoute: QuestionBankImportExportRoute,
  QuestionBankPracticeRoute: QuestionBankPracticeRoute,
  QuestionBankQuestionsRoute: QuestionBankQuestionsRoute,
  QuestionBankTagsRoute: QuestionBankTagsRoute,
  QuestionBankIndexRoute: QuestionBankIndexRoute,
}

const QuestionBankRouteRouteWithChildren =
  QuestionBankRouteRoute._addFileChildren(QuestionBankRouteRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiAdminRoleIdRouteChildren {
  ApiAdminRoleIdNavGroupsRoute: typeof ApiAdminRoleIdNavGroupsRoute
}

const ApiAdminRoleIdRouteChildren: ApiAdminRoleIdRouteChildren = {
  ApiAdminRoleIdNavGroupsRoute: ApiAdminRoleIdNavGroupsRoute,
}

const ApiAdminRoleIdRouteWithChildren = ApiAdminRoleIdRoute._addFileChildren(
  ApiAdminRoleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  QuestionBankRouteRoute: QuestionBankRouteRouteWithChildren,
  StudioRoute: StudioRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiI18nLngRoute: ApiI18nLngRoute,
  ApiAdminInvitationIdRoute: ApiAdminInvitationIdRoute,
  ApiAdminInvitationBatchRoute: ApiAdminInvitationBatchRoute,
  ApiAdminMemberIdRoute: ApiAdminMemberIdRoute,
  ApiAdminMemberBatchRoute: ApiAdminMemberBatchRoute,
  ApiAdminNavgroupIdRoute: ApiAdminNavgroupIdRoute,
  ApiAdminNavgroupOrderRoute: ApiAdminNavgroupOrderRoute,
  ApiAdminNavgroupVisibilityRoute: ApiAdminNavgroupVisibilityRoute,
  ApiAdminNavitemIdRoute: ApiAdminNavitemIdRoute,
  ApiAdminNavitemOrderRoute: ApiAdminNavitemOrderRoute,
  ApiAdminNavitemVisibilityRoute: ApiAdminNavitemVisibilityRoute,
  ApiAdminOrganizationIdRoute: ApiAdminOrganizationIdRoute,
  ApiAdminOrganizationBatchRoute: ApiAdminOrganizationBatchRoute,
  ApiAdminRoleIdRoute: ApiAdminRoleIdRouteWithChildren,
  ApiAdminSessionIdRoute: ApiAdminSessionIdRoute,
  ApiAdminTranslationIdRoute: ApiAdminTranslationIdRoute,
  ApiAdminTranslationExportRoute: ApiAdminTranslationExportRoute,
  ApiAdminTranslationImportRoute: ApiAdminTranslationImportRoute,
  ApiAdminUserIdRoute: ApiAdminUserIdRoute,
  ApiAdminUserBulkBanRoute: ApiAdminUserBulkBanRoute,
  ApiAdminUserBulkDeleteRoute: ApiAdminUserBulkDeleteRoute,
  ApiQuestionBankCategoriesIdRoute: ApiQuestionBankCategoriesIdRoute,
  ApiQuestionBankQuestionsIdRoute: ApiQuestionBankQuestionsIdRoute,
  ApiQuestionBankTagsIdRoute: ApiQuestionBankTagsIdRoute,
  ApiAdminInvitationIndexRoute: ApiAdminInvitationIndexRoute,
  ApiAdminLogIndexRoute: ApiAdminLogIndexRoute,
  ApiAdminMemberIndexRoute: ApiAdminMemberIndexRoute,
  ApiAdminNavgroupIndexRoute: ApiAdminNavgroupIndexRoute,
  ApiAdminNavitemIndexRoute: ApiAdminNavitemIndexRoute,
  ApiAdminOrganizationIndexRoute: ApiAdminOrganizationIndexRoute,
  ApiAdminRoleIndexRoute: ApiAdminRoleIndexRoute,
  ApiAdminSessionIndexRoute: ApiAdminSessionIndexRoute,
  ApiAdminTranslationIndexRoute: ApiAdminTranslationIndexRoute,
  ApiAdminUserIndexRoute: ApiAdminUserIndexRoute,
  ApiDemoTasksIndexRoute: ApiDemoTasksIndexRoute,
  ApiQuestionBankCategoriesIndexRoute: ApiQuestionBankCategoriesIndexRoute,
  ApiQuestionBankQuestionsIndexRoute: ApiQuestionBankQuestionsIndexRoute,
  ApiQuestionBankTagsIndexRoute: ApiQuestionBankTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
