/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as QuestionBankRouteRouteImport } from './routes/question-bank/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as QuestionBankIndexRouteImport } from './routes/question-bank/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as QuestionBankTagsRouteImport } from './routes/question-bank/tags'
import { Route as QuestionBankQuestionsRouteImport } from './routes/question-bank/questions'
import { Route as QuestionBankPracticeRouteImport } from './routes/question-bank/practice'
import { Route as QuestionBankImportExportRouteImport } from './routes/question-bank/import-export'
import { Route as QuestionBankCategoriesRouteImport } from './routes/question-bank/categories'
import { Route as QuestionBankAnalyticsRouteImport } from './routes/question-bank/analytics'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedDemoRouteRouteImport } from './routes/_authenticated/demo/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedDemoIndexRouteImport } from './routes/_authenticated/demo/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiUsersIdRouteImport } from './routes/api/users.$id'
import { Route as ApiI18nLngRouteImport } from './routes/api/i18n/$lng'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDemoProfileRouteImport } from './routes/_authenticated/demo/profile'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin/verification'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUserrolenavgroupRouteImport } from './routes/_authenticated/admin/userrolenavgroup'
import { Route as AuthenticatedAdminTranslationRouteImport } from './routes/_authenticated/admin/translation'
import { Route as AuthenticatedAdminSessionRouteImport } from './routes/_authenticated/admin/session'
import { Route as AuthenticatedAdminRolenavgroupRouteImport } from './routes/_authenticated/admin/rolenavgroup'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin/organizations'
import { Route as AuthenticatedAdminNavigationRouteImport } from './routes/_authenticated/admin/navigation'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminLogRouteImport } from './routes/_authenticated/admin/log'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin/invitations'
import { Route as AuthenticatedAdminDepartmentRouteImport } from './routes/_authenticated/admin/department'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes/_authenticated/admin/account'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedDemoSettingsRouteRouteImport } from './routes/_authenticated/demo/settings/route'
import { Route as ApiQuestionBankTagsIndexRouteImport } from './routes/api/question-bank/tags/index'
import { Route as ApiQuestionBankQuestionsIndexRouteImport } from './routes/api/question-bank/questions/index'
import { Route as ApiQuestionBankCategoriesIndexRouteImport } from './routes/api/question-bank/categories/index'
import { Route as ApiDemoTasksIndexRouteImport } from './routes/api/demo/tasks/index'
import { Route as AuthenticatedDemoUsersIndexRouteImport } from './routes/_authenticated/demo/users/index'
import { Route as AuthenticatedDemoTasksIndexRouteImport } from './routes/_authenticated/demo/tasks/index'
import { Route as AuthenticatedDemoSettingsIndexRouteImport } from './routes/_authenticated/demo/settings/index'
import { Route as AuthenticatedDemoChatsIndexRouteImport } from './routes/_authenticated/demo/chats/index'
import { Route as AuthenticatedDemoAppsIndexRouteImport } from './routes/_authenticated/demo/apps/index'
import { Route as AuthenticatedAppHelpCenterIndexRouteImport } from './routes/_authenticated/_app/help-center/index'
import { Route as ApiQuestionBankTagsIdRouteImport } from './routes/api/question-bank/tags/$id'
import { Route as ApiQuestionBankQuestionsIdRouteImport } from './routes/api/question-bank/questions/$id'
import { Route as ApiQuestionBankCategoriesIdRouteImport } from './routes/api/question-bank/categories/$id'
import { Route as AuthenticatedDemoSettingsNotificationsRouteImport } from './routes/_authenticated/demo/settings/notifications'
import { Route as AuthenticatedDemoSettingsDisplayRouteImport } from './routes/_authenticated/demo/settings/display'
import { Route as AuthenticatedDemoSettingsAppearanceRouteImport } from './routes/_authenticated/demo/settings/appearance'
import { Route as AuthenticatedDemoSettingsAccountRouteImport } from './routes/_authenticated/demo/settings/account'
import { Route as AuthenticatedAdminRbacRolesRouteImport } from './routes/_authenticated/admin/rbac/roles'
import { Route as AuthenticatedAdminRbacPermissionsRouteImport } from './routes/_authenticated/admin/rbac/permissions'
import { Route as AuthenticatedAdminRbacOrgRolesRouteImport } from './routes/_authenticated/admin/rbac/org-roles'
import { Route as AuthenticatedAppErrorsErrorRouteImport } from './routes/_authenticated/_app/errors/$error'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRouteRoute = QuestionBankRouteRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankIndexRoute = QuestionBankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const QuestionBankTagsRoute = QuestionBankTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankQuestionsRoute = QuestionBankQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankPracticeRoute = QuestionBankPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankImportExportRoute =
  QuestionBankImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => QuestionBankRouteRoute,
  } as any)
const QuestionBankCategoriesRoute = QuestionBankCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const QuestionBankAnalyticsRoute = QuestionBankAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => QuestionBankRouteRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoRouteRoute = AuthenticatedDemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoIndexRoute = AuthenticatedDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDemoRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiI18nLngRoute = ApiI18nLngRouteImport.update({
  id: '/api/i18n/$lng',
  path: '/api/i18n/$lng',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoProfileRoute =
  AuthenticatedDemoProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUserrolenavgroupRoute =
  AuthenticatedAdminUserrolenavgroupRouteImport.update({
    id: '/userrolenavgroup',
    path: '/userrolenavgroup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTranslationRoute =
  AuthenticatedAdminTranslationRouteImport.update({
    id: '/translation',
    path: '/translation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSessionRoute =
  AuthenticatedAdminSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolenavgroupRoute =
  AuthenticatedAdminRolenavgroupRouteImport.update({
    id: '/rolenavgroup',
    path: '/rolenavgroup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNavigationRoute =
  AuthenticatedAdminNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogRoute = AuthenticatedAdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentRoute =
  AuthenticatedAdminDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedDemoSettingsRouteRoute =
  AuthenticatedDemoSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const ApiQuestionBankTagsIndexRoute =
  ApiQuestionBankTagsIndexRouteImport.update({
    id: '/api/question-bank/tags/',
    path: '/api/question-bank/tags/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankQuestionsIndexRoute =
  ApiQuestionBankQuestionsIndexRouteImport.update({
    id: '/api/question-bank/questions/',
    path: '/api/question-bank/questions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankCategoriesIndexRoute =
  ApiQuestionBankCategoriesIndexRouteImport.update({
    id: '/api/question-bank/categories/',
    path: '/api/question-bank/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDemoTasksIndexRoute = ApiDemoTasksIndexRouteImport.update({
  id: '/api/demo/tasks/',
  path: '/api/demo/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoUsersIndexRoute =
  AuthenticatedDemoUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const AuthenticatedDemoTasksIndexRoute =
  AuthenticatedDemoTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const AuthenticatedDemoSettingsIndexRoute =
  AuthenticatedDemoSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoChatsIndexRoute =
  AuthenticatedDemoChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const AuthenticatedDemoAppsIndexRoute =
  AuthenticatedDemoAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => AuthenticatedDemoRouteRoute,
  } as any)
const AuthenticatedAppHelpCenterIndexRoute =
  AuthenticatedAppHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const ApiQuestionBankTagsIdRoute = ApiQuestionBankTagsIdRouteImport.update({
  id: '/api/question-bank/tags/$id',
  path: '/api/question-bank/tags/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionBankQuestionsIdRoute =
  ApiQuestionBankQuestionsIdRouteImport.update({
    id: '/api/question-bank/questions/$id',
    path: '/api/question-bank/questions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionBankCategoriesIdRoute =
  ApiQuestionBankCategoriesIdRouteImport.update({
    id: '/api/question-bank/categories/$id',
    path: '/api/question-bank/categories/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDemoSettingsNotificationsRoute =
  AuthenticatedDemoSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsDisplayRoute =
  AuthenticatedDemoSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAppearanceRoute =
  AuthenticatedDemoSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedDemoSettingsAccountRoute =
  AuthenticatedDemoSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDemoSettingsRouteRoute,
  } as any)
const AuthenticatedAdminRbacRolesRoute =
  AuthenticatedAdminRbacRolesRouteImport.update({
    id: '/rbac/roles',
    path: '/rbac/roles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRbacPermissionsRoute =
  AuthenticatedAdminRbacPermissionsRouteImport.update({
    id: '/rbac/permissions',
    path: '/rbac/permissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRbacOrgRolesRoute =
  AuthenticatedAdminRbacOrgRolesRouteImport.update({
    id: '/rbac/org-roles',
    path: '/rbac/org-roles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppErrorsErrorRoute =
  AuthenticatedAppErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/question-bank': typeof QuestionBankRouteRouteWithChildren
  '/studio': typeof StudioRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/demo': typeof AuthenticatedDemoRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/question-bank/': typeof QuestionBankIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/department': typeof AuthenticatedAdminDepartmentRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/admin/session': typeof AuthenticatedAdminSessionRoute
  '/admin/translation': typeof AuthenticatedAdminTranslationRoute
  '/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/demo/profile': typeof AuthenticatedDemoProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/demo/': typeof AuthenticatedDemoIndexRoute
  '/errors/$error': typeof AuthenticatedAppErrorsErrorRoute
  '/admin/rbac/org-roles': typeof AuthenticatedAdminRbacOrgRolesRoute
  '/admin/rbac/permissions': typeof AuthenticatedAdminRbacPermissionsRoute
  '/admin/rbac/roles': typeof AuthenticatedAdminRbacRolesRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/help-center/': typeof AuthenticatedAppHelpCenterIndexRoute
  '/demo/apps/': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats/': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks/': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users/': typeof AuthenticatedDemoUsersIndexRoute
  '/api/demo/tasks/': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories/': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions/': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags/': typeof ApiQuestionBankTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/studio': typeof StudioRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/question-bank': typeof QuestionBankIndexRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/department': typeof AuthenticatedAdminDepartmentRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/admin/session': typeof AuthenticatedAdminSessionRoute
  '/admin/translation': typeof AuthenticatedAdminTranslationRoute
  '/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/demo/profile': typeof AuthenticatedDemoProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/demo': typeof AuthenticatedDemoIndexRoute
  '/errors/$error': typeof AuthenticatedAppErrorsErrorRoute
  '/admin/rbac/org-roles': typeof AuthenticatedAdminRbacOrgRolesRoute
  '/admin/rbac/permissions': typeof AuthenticatedAdminRbacPermissionsRoute
  '/admin/rbac/roles': typeof AuthenticatedAdminRbacRolesRoute
  '/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/help-center': typeof AuthenticatedAppHelpCenterIndexRoute
  '/demo/apps': typeof AuthenticatedDemoAppsIndexRoute
  '/demo/chats': typeof AuthenticatedDemoChatsIndexRoute
  '/demo/settings': typeof AuthenticatedDemoSettingsIndexRoute
  '/demo/tasks': typeof AuthenticatedDemoTasksIndexRoute
  '/demo/users': typeof AuthenticatedDemoUsersIndexRoute
  '/api/demo/tasks': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags': typeof ApiQuestionBankTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/question-bank': typeof QuestionBankRouteRouteWithChildren
  '/studio': typeof StudioRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/demo': typeof AuthenticatedDemoRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(public)/about': typeof publicAboutRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/question-bank/analytics': typeof QuestionBankAnalyticsRoute
  '/question-bank/categories': typeof QuestionBankCategoriesRoute
  '/question-bank/import-export': typeof QuestionBankImportExportRoute
  '/question-bank/practice': typeof QuestionBankPracticeRoute
  '/question-bank/questions': typeof QuestionBankQuestionsRoute
  '/question-bank/tags': typeof QuestionBankTagsRoute
  '/(public)/': typeof publicIndexRoute
  '/question-bank/': typeof QuestionBankIndexRoute
  '/_authenticated/demo/settings': typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/department': typeof AuthenticatedAdminDepartmentRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/admin/log': typeof AuthenticatedAdminLogRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/_authenticated/admin/session': typeof AuthenticatedAdminSessionRoute
  '/_authenticated/admin/translation': typeof AuthenticatedAdminTranslationRoute
  '/_authenticated/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/demo/profile': typeof AuthenticatedDemoProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/i18n/$lng': typeof ApiI18nLngRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/demo/': typeof AuthenticatedDemoIndexRoute
  '/_authenticated/_app/errors/$error': typeof AuthenticatedAppErrorsErrorRoute
  '/_authenticated/admin/rbac/org-roles': typeof AuthenticatedAdminRbacOrgRolesRoute
  '/_authenticated/admin/rbac/permissions': typeof AuthenticatedAdminRbacPermissionsRoute
  '/_authenticated/admin/rbac/roles': typeof AuthenticatedAdminRbacRolesRoute
  '/_authenticated/demo/settings/account': typeof AuthenticatedDemoSettingsAccountRoute
  '/_authenticated/demo/settings/appearance': typeof AuthenticatedDemoSettingsAppearanceRoute
  '/_authenticated/demo/settings/display': typeof AuthenticatedDemoSettingsDisplayRoute
  '/_authenticated/demo/settings/notifications': typeof AuthenticatedDemoSettingsNotificationsRoute
  '/api/question-bank/categories/$id': typeof ApiQuestionBankCategoriesIdRoute
  '/api/question-bank/questions/$id': typeof ApiQuestionBankQuestionsIdRoute
  '/api/question-bank/tags/$id': typeof ApiQuestionBankTagsIdRoute
  '/_authenticated/_app/help-center/': typeof AuthenticatedAppHelpCenterIndexRoute
  '/_authenticated/demo/apps/': typeof AuthenticatedDemoAppsIndexRoute
  '/_authenticated/demo/chats/': typeof AuthenticatedDemoChatsIndexRoute
  '/_authenticated/demo/settings/': typeof AuthenticatedDemoSettingsIndexRoute
  '/_authenticated/demo/tasks/': typeof AuthenticatedDemoTasksIndexRoute
  '/_authenticated/demo/users/': typeof AuthenticatedDemoUsersIndexRoute
  '/api/demo/tasks/': typeof ApiDemoTasksIndexRoute
  '/api/question-bank/categories/': typeof ApiQuestionBankCategoriesIndexRoute
  '/api/question-bank/questions/': typeof ApiQuestionBankQuestionsIndexRoute
  '/api/question-bank/tags/': typeof ApiQuestionBankTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/question-bank'
    | '/studio'
    | '/admin'
    | '/demo'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/question-bank/'
    | '/demo/settings'
    | '/dashboard'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/department'
    | '/admin/invitations'
    | '/admin/log'
    | '/admin/members'
    | '/admin/navigation'
    | '/admin/organizations'
    | '/admin/rolenavgroup'
    | '/admin/session'
    | '/admin/translation'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/demo/profile'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/admin/'
    | '/demo/'
    | '/errors/$error'
    | '/admin/rbac/org-roles'
    | '/admin/rbac/permissions'
    | '/admin/rbac/roles'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/help-center/'
    | '/demo/apps/'
    | '/demo/chats/'
    | '/demo/settings/'
    | '/demo/tasks/'
    | '/demo/users/'
    | '/api/demo/tasks/'
    | '/api/question-bank/categories/'
    | '/api/question-bank/questions/'
    | '/api/question-bank/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/studio'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/question-bank'
    | '/dashboard'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/department'
    | '/admin/invitations'
    | '/admin/log'
    | '/admin/members'
    | '/admin/navigation'
    | '/admin/organizations'
    | '/admin/rolenavgroup'
    | '/admin/session'
    | '/admin/translation'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/demo/profile'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/admin'
    | '/demo'
    | '/errors/$error'
    | '/admin/rbac/org-roles'
    | '/admin/rbac/permissions'
    | '/admin/rbac/roles'
    | '/demo/settings/account'
    | '/demo/settings/appearance'
    | '/demo/settings/display'
    | '/demo/settings/notifications'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/help-center'
    | '/demo/apps'
    | '/demo/chats'
    | '/demo/settings'
    | '/demo/tasks'
    | '/demo/users'
    | '/api/demo/tasks'
    | '/api/question-bank/categories'
    | '/api/question-bank/questions'
    | '/api/question-bank/tags'
  id:
    | '__root__'
    | '/(public)'
    | '/_authenticated'
    | '/question-bank'
    | '/studio'
    | '/_authenticated/_app'
    | '/_authenticated/admin'
    | '/_authenticated/demo'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(public)/about'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/api/sessions'
    | '/api/users'
    | '/question-bank/analytics'
    | '/question-bank/categories'
    | '/question-bank/import-export'
    | '/question-bank/practice'
    | '/question-bank/questions'
    | '/question-bank/tags'
    | '/(public)/'
    | '/question-bank/'
    | '/_authenticated/demo/settings'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/department'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/admin/log'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/navigation'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/rolenavgroup'
    | '/_authenticated/admin/session'
    | '/_authenticated/admin/translation'
    | '/_authenticated/admin/userrolenavgroup'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verification'
    | '/_authenticated/demo/profile'
    | '/api/auth/$'
    | '/api/i18n/$lng'
    | '/api/users/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/demo/'
    | '/_authenticated/_app/errors/$error'
    | '/_authenticated/admin/rbac/org-roles'
    | '/_authenticated/admin/rbac/permissions'
    | '/_authenticated/admin/rbac/roles'
    | '/_authenticated/demo/settings/account'
    | '/_authenticated/demo/settings/appearance'
    | '/_authenticated/demo/settings/display'
    | '/_authenticated/demo/settings/notifications'
    | '/api/question-bank/categories/$id'
    | '/api/question-bank/questions/$id'
    | '/api/question-bank/tags/$id'
    | '/_authenticated/_app/help-center/'
    | '/_authenticated/demo/apps/'
    | '/_authenticated/demo/chats/'
    | '/_authenticated/demo/settings/'
    | '/_authenticated/demo/tasks/'
    | '/_authenticated/demo/users/'
    | '/api/demo/tasks/'
    | '/api/question-bank/categories/'
    | '/api/question-bank/questions/'
    | '/api/question-bank/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  QuestionBankRouteRoute: typeof QuestionBankRouteRouteWithChildren
  StudioRoute: typeof StudioRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiI18nLngRoute: typeof ApiI18nLngRoute
  ApiQuestionBankCategoriesIdRoute: typeof ApiQuestionBankCategoriesIdRoute
  ApiQuestionBankQuestionsIdRoute: typeof ApiQuestionBankQuestionsIdRoute
  ApiQuestionBankTagsIdRoute: typeof ApiQuestionBankTagsIdRoute
  ApiDemoTasksIndexRoute: typeof ApiDemoTasksIndexRoute
  ApiQuestionBankCategoriesIndexRoute: typeof ApiQuestionBankCategoriesIndexRoute
  ApiQuestionBankQuestionsIndexRoute: typeof ApiQuestionBankQuestionsIndexRoute
  ApiQuestionBankTagsIndexRoute: typeof ApiQuestionBankTagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank/': {
      id: '/question-bank/'
      path: '/'
      fullPath: '/question-bank/'
      preLoaderRoute: typeof QuestionBankIndexRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/question-bank/tags': {
      id: '/question-bank/tags'
      path: '/tags'
      fullPath: '/question-bank/tags'
      preLoaderRoute: typeof QuestionBankTagsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/questions': {
      id: '/question-bank/questions'
      path: '/questions'
      fullPath: '/question-bank/questions'
      preLoaderRoute: typeof QuestionBankQuestionsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/practice': {
      id: '/question-bank/practice'
      path: '/practice'
      fullPath: '/question-bank/practice'
      preLoaderRoute: typeof QuestionBankPracticeRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/import-export': {
      id: '/question-bank/import-export'
      path: '/import-export'
      fullPath: '/question-bank/import-export'
      preLoaderRoute: typeof QuestionBankImportExportRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/categories': {
      id: '/question-bank/categories'
      path: '/categories'
      fullPath: '/question-bank/categories'
      preLoaderRoute: typeof QuestionBankCategoriesRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/question-bank/analytics': {
      id: '/question-bank/analytics'
      path: '/analytics'
      fullPath: '/question-bank/analytics'
      preLoaderRoute: typeof QuestionBankAnalyticsRouteImport
      parentRoute: typeof QuestionBankRouteRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/': {
      id: '/_authenticated/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof AuthenticatedDemoIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/i18n/$lng': {
      id: '/api/i18n/$lng'
      path: '/api/i18n/$lng'
      fullPath: '/api/i18n/$lng'
      preLoaderRoute: typeof ApiI18nLngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/profile': {
      id: '/_authenticated/demo/profile'
      path: '/profile'
      fullPath: '/demo/profile'
      preLoaderRoute: typeof AuthenticatedDemoProfileRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/userrolenavgroup': {
      id: '/_authenticated/admin/userrolenavgroup'
      path: '/userrolenavgroup'
      fullPath: '/admin/userrolenavgroup'
      preLoaderRoute: typeof AuthenticatedAdminUserrolenavgroupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/translation': {
      id: '/_authenticated/admin/translation'
      path: '/translation'
      fullPath: '/admin/translation'
      preLoaderRoute: typeof AuthenticatedAdminTranslationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/session': {
      id: '/_authenticated/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AuthenticatedAdminSessionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rolenavgroup': {
      id: '/_authenticated/admin/rolenavgroup'
      path: '/rolenavgroup'
      fullPath: '/admin/rolenavgroup'
      preLoaderRoute: typeof AuthenticatedAdminRolenavgroupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/navigation': {
      id: '/_authenticated/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AuthenticatedAdminNavigationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/log': {
      id: '/_authenticated/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AuthenticatedAdminLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/department': {
      id: '/_authenticated/admin/department'
      path: '/department'
      fullPath: '/admin/department'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/demo/settings': {
      id: '/_authenticated/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof AuthenticatedDemoSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/api/question-bank/tags/': {
      id: '/api/question-bank/tags/'
      path: '/api/question-bank/tags'
      fullPath: '/api/question-bank/tags/'
      preLoaderRoute: typeof ApiQuestionBankTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/questions/': {
      id: '/api/question-bank/questions/'
      path: '/api/question-bank/questions'
      fullPath: '/api/question-bank/questions/'
      preLoaderRoute: typeof ApiQuestionBankQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/categories/': {
      id: '/api/question-bank/categories/'
      path: '/api/question-bank/categories'
      fullPath: '/api/question-bank/categories/'
      preLoaderRoute: typeof ApiQuestionBankCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/tasks/': {
      id: '/api/demo/tasks/'
      path: '/api/demo/tasks'
      fullPath: '/api/demo/tasks/'
      preLoaderRoute: typeof ApiDemoTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/users/': {
      id: '/_authenticated/demo/users/'
      path: '/users'
      fullPath: '/demo/users/'
      preLoaderRoute: typeof AuthenticatedDemoUsersIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/demo/tasks/': {
      id: '/_authenticated/demo/tasks/'
      path: '/tasks'
      fullPath: '/demo/tasks/'
      preLoaderRoute: typeof AuthenticatedDemoTasksIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/demo/settings/': {
      id: '/_authenticated/demo/settings/'
      path: '/'
      fullPath: '/demo/settings/'
      preLoaderRoute: typeof AuthenticatedDemoSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/chats/': {
      id: '/_authenticated/demo/chats/'
      path: '/chats'
      fullPath: '/demo/chats/'
      preLoaderRoute: typeof AuthenticatedDemoChatsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/demo/apps/': {
      id: '/_authenticated/demo/apps/'
      path: '/apps'
      fullPath: '/demo/apps/'
      preLoaderRoute: typeof AuthenticatedDemoAppsIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRouteRoute
    }
    '/_authenticated/_app/help-center/': {
      id: '/_authenticated/_app/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedAppHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/api/question-bank/tags/$id': {
      id: '/api/question-bank/tags/$id'
      path: '/api/question-bank/tags/$id'
      fullPath: '/api/question-bank/tags/$id'
      preLoaderRoute: typeof ApiQuestionBankTagsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/questions/$id': {
      id: '/api/question-bank/questions/$id'
      path: '/api/question-bank/questions/$id'
      fullPath: '/api/question-bank/questions/$id'
      preLoaderRoute: typeof ApiQuestionBankQuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/question-bank/categories/$id': {
      id: '/api/question-bank/categories/$id'
      path: '/api/question-bank/categories/$id'
      fullPath: '/api/question-bank/categories/$id'
      preLoaderRoute: typeof ApiQuestionBankCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo/settings/notifications': {
      id: '/_authenticated/demo/settings/notifications'
      path: '/notifications'
      fullPath: '/demo/settings/notifications'
      preLoaderRoute: typeof AuthenticatedDemoSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/display': {
      id: '/_authenticated/demo/settings/display'
      path: '/display'
      fullPath: '/demo/settings/display'
      preLoaderRoute: typeof AuthenticatedDemoSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/appearance': {
      id: '/_authenticated/demo/settings/appearance'
      path: '/appearance'
      fullPath: '/demo/settings/appearance'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/demo/settings/account': {
      id: '/_authenticated/demo/settings/account'
      path: '/account'
      fullPath: '/demo/settings/account'
      preLoaderRoute: typeof AuthenticatedDemoSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedDemoSettingsRouteRoute
    }
    '/_authenticated/admin/rbac/roles': {
      id: '/_authenticated/admin/rbac/roles'
      path: '/rbac/roles'
      fullPath: '/admin/rbac/roles'
      preLoaderRoute: typeof AuthenticatedAdminRbacRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rbac/permissions': {
      id: '/_authenticated/admin/rbac/permissions'
      path: '/rbac/permissions'
      fullPath: '/admin/rbac/permissions'
      preLoaderRoute: typeof AuthenticatedAdminRbacPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rbac/org-roles': {
      id: '/_authenticated/admin/rbac/org-roles'
      path: '/rbac/org-roles'
      fullPath: '/admin/rbac/org-roles'
      preLoaderRoute: typeof AuthenticatedAdminRbacOrgRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/errors/$error': {
      id: '/_authenticated/_app/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedAppErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppErrorsErrorRoute: typeof AuthenticatedAppErrorsErrorRoute
  AuthenticatedAppHelpCenterIndexRoute: typeof AuthenticatedAppHelpCenterIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppErrorsErrorRoute: AuthenticatedAppErrorsErrorRoute,
  AuthenticatedAppHelpCenterIndexRoute: AuthenticatedAppHelpCenterIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDepartmentRoute: typeof AuthenticatedAdminDepartmentRoute
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
  AuthenticatedAdminLogRoute: typeof AuthenticatedAdminLogRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminNavigationRoute: typeof AuthenticatedAdminNavigationRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminRolenavgroupRoute: typeof AuthenticatedAdminRolenavgroupRoute
  AuthenticatedAdminSessionRoute: typeof AuthenticatedAdminSessionRoute
  AuthenticatedAdminTranslationRoute: typeof AuthenticatedAdminTranslationRoute
  AuthenticatedAdminUserrolenavgroupRoute: typeof AuthenticatedAdminUserrolenavgroupRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminRbacOrgRolesRoute: typeof AuthenticatedAdminRbacOrgRolesRoute
  AuthenticatedAdminRbacPermissionsRoute: typeof AuthenticatedAdminRbacPermissionsRoute
  AuthenticatedAdminRbacRolesRoute: typeof AuthenticatedAdminRbacRolesRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminDepartmentRoute: AuthenticatedAdminDepartmentRoute,
    AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
    AuthenticatedAdminLogRoute: AuthenticatedAdminLogRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
    AuthenticatedAdminNavigationRoute: AuthenticatedAdminNavigationRoute,
    AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
    AuthenticatedAdminRolenavgroupRoute: AuthenticatedAdminRolenavgroupRoute,
    AuthenticatedAdminSessionRoute: AuthenticatedAdminSessionRoute,
    AuthenticatedAdminTranslationRoute: AuthenticatedAdminTranslationRoute,
    AuthenticatedAdminUserrolenavgroupRoute:
      AuthenticatedAdminUserrolenavgroupRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminRbacOrgRolesRoute: AuthenticatedAdminRbacOrgRolesRoute,
    AuthenticatedAdminRbacPermissionsRoute:
      AuthenticatedAdminRbacPermissionsRoute,
    AuthenticatedAdminRbacRolesRoute: AuthenticatedAdminRbacRolesRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDemoSettingsRouteRouteChildren {
  AuthenticatedDemoSettingsAccountRoute: typeof AuthenticatedDemoSettingsAccountRoute
  AuthenticatedDemoSettingsAppearanceRoute: typeof AuthenticatedDemoSettingsAppearanceRoute
  AuthenticatedDemoSettingsDisplayRoute: typeof AuthenticatedDemoSettingsDisplayRoute
  AuthenticatedDemoSettingsNotificationsRoute: typeof AuthenticatedDemoSettingsNotificationsRoute
  AuthenticatedDemoSettingsIndexRoute: typeof AuthenticatedDemoSettingsIndexRoute
}

const AuthenticatedDemoSettingsRouteRouteChildren: AuthenticatedDemoSettingsRouteRouteChildren =
  {
    AuthenticatedDemoSettingsAccountRoute:
      AuthenticatedDemoSettingsAccountRoute,
    AuthenticatedDemoSettingsAppearanceRoute:
      AuthenticatedDemoSettingsAppearanceRoute,
    AuthenticatedDemoSettingsDisplayRoute:
      AuthenticatedDemoSettingsDisplayRoute,
    AuthenticatedDemoSettingsNotificationsRoute:
      AuthenticatedDemoSettingsNotificationsRoute,
    AuthenticatedDemoSettingsIndexRoute: AuthenticatedDemoSettingsIndexRoute,
  }

const AuthenticatedDemoSettingsRouteRouteWithChildren =
  AuthenticatedDemoSettingsRouteRoute._addFileChildren(
    AuthenticatedDemoSettingsRouteRouteChildren,
  )

interface AuthenticatedDemoRouteRouteChildren {
  AuthenticatedDemoSettingsRouteRoute: typeof AuthenticatedDemoSettingsRouteRouteWithChildren
  AuthenticatedDemoProfileRoute: typeof AuthenticatedDemoProfileRoute
  AuthenticatedDemoIndexRoute: typeof AuthenticatedDemoIndexRoute
  AuthenticatedDemoAppsIndexRoute: typeof AuthenticatedDemoAppsIndexRoute
  AuthenticatedDemoChatsIndexRoute: typeof AuthenticatedDemoChatsIndexRoute
  AuthenticatedDemoTasksIndexRoute: typeof AuthenticatedDemoTasksIndexRoute
  AuthenticatedDemoUsersIndexRoute: typeof AuthenticatedDemoUsersIndexRoute
}

const AuthenticatedDemoRouteRouteChildren: AuthenticatedDemoRouteRouteChildren =
  {
    AuthenticatedDemoSettingsRouteRoute:
      AuthenticatedDemoSettingsRouteRouteWithChildren,
    AuthenticatedDemoProfileRoute: AuthenticatedDemoProfileRoute,
    AuthenticatedDemoIndexRoute: AuthenticatedDemoIndexRoute,
    AuthenticatedDemoAppsIndexRoute: AuthenticatedDemoAppsIndexRoute,
    AuthenticatedDemoChatsIndexRoute: AuthenticatedDemoChatsIndexRoute,
    AuthenticatedDemoTasksIndexRoute: AuthenticatedDemoTasksIndexRoute,
    AuthenticatedDemoUsersIndexRoute: AuthenticatedDemoUsersIndexRoute,
  }

const AuthenticatedDemoRouteRouteWithChildren =
  AuthenticatedDemoRouteRoute._addFileChildren(
    AuthenticatedDemoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDemoRouteRoute: typeof AuthenticatedDemoRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDemoRouteRoute: AuthenticatedDemoRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface QuestionBankRouteRouteChildren {
  QuestionBankAnalyticsRoute: typeof QuestionBankAnalyticsRoute
  QuestionBankCategoriesRoute: typeof QuestionBankCategoriesRoute
  QuestionBankImportExportRoute: typeof QuestionBankImportExportRoute
  QuestionBankPracticeRoute: typeof QuestionBankPracticeRoute
  QuestionBankQuestionsRoute: typeof QuestionBankQuestionsRoute
  QuestionBankTagsRoute: typeof QuestionBankTagsRoute
  QuestionBankIndexRoute: typeof QuestionBankIndexRoute
}

const QuestionBankRouteRouteChildren: QuestionBankRouteRouteChildren = {
  QuestionBankAnalyticsRoute: QuestionBankAnalyticsRoute,
  QuestionBankCategoriesRoute: QuestionBankCategoriesRoute,
  QuestionBankImportExportRoute: QuestionBankImportExportRoute,
  QuestionBankPracticeRoute: QuestionBankPracticeRoute,
  QuestionBankQuestionsRoute: QuestionBankQuestionsRoute,
  QuestionBankTagsRoute: QuestionBankTagsRoute,
  QuestionBankIndexRoute: QuestionBankIndexRoute,
}

const QuestionBankRouteRouteWithChildren =
  QuestionBankRouteRoute._addFileChildren(QuestionBankRouteRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  QuestionBankRouteRoute: QuestionBankRouteRouteWithChildren,
  StudioRoute: StudioRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiI18nLngRoute: ApiI18nLngRoute,
  ApiQuestionBankCategoriesIdRoute: ApiQuestionBankCategoriesIdRoute,
  ApiQuestionBankQuestionsIdRoute: ApiQuestionBankQuestionsIdRoute,
  ApiQuestionBankTagsIdRoute: ApiQuestionBankTagsIdRoute,
  ApiDemoTasksIndexRoute: ApiDemoTasksIndexRoute,
  ApiQuestionBankCategoriesIndexRoute: ApiQuestionBankCategoriesIndexRoute,
  ApiQuestionBankQuestionsIndexRoute: ApiQuestionBankQuestionsIndexRoute,
  ApiQuestionBankTagsIndexRoute: ApiQuestionBankTagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
