/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin/verification'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminUserrolenavgroupRouteImport } from './routes/_authenticated/admin/userrolenavgroup'
import { Route as AuthenticatedAdminUserRouteImport } from './routes/_authenticated/admin/user'
import { Route as AuthenticatedAdminSessionRouteImport } from './routes/_authenticated/admin/session'
import { Route as AuthenticatedAdminRolenavgroupRouteImport } from './routes/_authenticated/admin/rolenavgroup'
import { Route as AuthenticatedAdminOrganizationRouteImport } from './routes/_authenticated/admin/organization'
import { Route as AuthenticatedAdminNavitemRouteImport } from './routes/_authenticated/admin/navitem'
import { Route as AuthenticatedAdminNavgroupRouteImport } from './routes/_authenticated/admin/navgroup'
import { Route as AuthenticatedAdminMemberRouteImport } from './routes/_authenticated/admin/member'
import { Route as AuthenticatedAdminInvitationRouteImport } from './routes/_authenticated/admin/invitation'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes/_authenticated/admin/account'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api/users'
import { ServerRoute as ApiSessionsServerRouteImport } from './routes/api/sessions'
import { ServerRoute as ApiUsersIdServerRouteImport } from './routes/api/users.$id'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiAdminUserIndexServerRouteImport } from './routes/api/admin/user/index'
import { ServerRoute as ApiAdminNavitemIndexServerRouteImport } from './routes/api/admin/navitem/index'
import { ServerRoute as ApiAdminNavgroupIndexServerRouteImport } from './routes/api/admin/navgroup/index'
import { ServerRoute as ApiAdminNavitemVisibilityServerRouteImport } from './routes/api/admin/navitem/visibility'
import { ServerRoute as ApiAdminNavitemOrderServerRouteImport } from './routes/api/admin/navitem/order'
import { ServerRoute as ApiAdminNavitemIdServerRouteImport } from './routes/api/admin/navitem/$id'
import { ServerRoute as ApiAdminNavgroupVisibilityServerRouteImport } from './routes/api/admin/navgroup/visibility'
import { ServerRoute as ApiAdminNavgroupOrderServerRouteImport } from './routes/api/admin/navgroup/order'
import { ServerRoute as ApiAdminNavgroupIdServerRouteImport } from './routes/api/admin/navgroup/$id'

const rootServerRouteImport = createServerRootRoute()

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/admin/verification',
    path: '/admin/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUserrolenavgroupRoute =
  AuthenticatedAdminUserrolenavgroupRouteImport.update({
    id: '/admin/userrolenavgroup',
    path: '/admin/userrolenavgroup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUserRoute = AuthenticatedAdminUserRouteImport.update({
  id: '/admin/user',
  path: '/admin/user',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSessionRoute =
  AuthenticatedAdminSessionRouteImport.update({
    id: '/admin/session',
    path: '/admin/session',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolenavgroupRoute =
  AuthenticatedAdminRolenavgroupRouteImport.update({
    id: '/admin/rolenavgroup',
    path: '/admin/rolenavgroup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationRoute =
  AuthenticatedAdminOrganizationRouteImport.update({
    id: '/admin/organization',
    path: '/admin/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNavitemRoute =
  AuthenticatedAdminNavitemRouteImport.update({
    id: '/admin/navitem',
    path: '/admin/navitem',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNavgroupRoute =
  AuthenticatedAdminNavgroupRouteImport.update({
    id: '/admin/navgroup',
    path: '/admin/navgroup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMemberRoute =
  AuthenticatedAdminMemberRouteImport.update({
    id: '/admin/member',
    path: '/admin/member',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvitationRoute =
  AuthenticatedAdminInvitationRouteImport.update({
    id: '/admin/invitation',
    path: '/admin/invitation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/admin/account',
    path: '/admin/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSessionsServerRoute = ApiSessionsServerRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersIdServerRoute = ApiUsersIdServerRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersServerRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAdminUserIndexServerRoute = ApiAdminUserIndexServerRouteImport.update({
  id: '/api/admin/user/',
  path: '/api/admin/user/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAdminNavitemIndexServerRoute =
  ApiAdminNavitemIndexServerRouteImport.update({
    id: '/api/admin/navitem/',
    path: '/api/admin/navitem/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavgroupIndexServerRoute =
  ApiAdminNavgroupIndexServerRouteImport.update({
    id: '/api/admin/navgroup/',
    path: '/api/admin/navgroup/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavitemVisibilityServerRoute =
  ApiAdminNavitemVisibilityServerRouteImport.update({
    id: '/api/admin/navitem/visibility',
    path: '/api/admin/navitem/visibility',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavitemOrderServerRoute =
  ApiAdminNavitemOrderServerRouteImport.update({
    id: '/api/admin/navitem/order',
    path: '/api/admin/navitem/order',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavitemIdServerRoute = ApiAdminNavitemIdServerRouteImport.update({
  id: '/api/admin/navitem/$id',
  path: '/api/admin/navitem/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAdminNavgroupVisibilityServerRoute =
  ApiAdminNavgroupVisibilityServerRouteImport.update({
    id: '/api/admin/navgroup/visibility',
    path: '/api/admin/navgroup/visibility',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavgroupOrderServerRoute =
  ApiAdminNavgroupOrderServerRouteImport.update({
    id: '/api/admin/navgroup/order',
    path: '/api/admin/navgroup/order',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminNavgroupIdServerRoute =
  ApiAdminNavgroupIdServerRouteImport.update({
    id: '/api/admin/navgroup/$id',
    path: '/api/admin/navgroup/$id',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/invitation': typeof AuthenticatedAdminInvitationRoute
  '/admin/member': typeof AuthenticatedAdminMemberRoute
  '/admin/navgroup': typeof AuthenticatedAdminNavgroupRoute
  '/admin/navitem': typeof AuthenticatedAdminNavitemRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/admin/session': typeof AuthenticatedAdminSessionRoute
  '/admin/user': typeof AuthenticatedAdminUserRoute
  '/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/invitation': typeof AuthenticatedAdminInvitationRoute
  '/admin/member': typeof AuthenticatedAdminMemberRoute
  '/admin/navgroup': typeof AuthenticatedAdminNavgroupRoute
  '/admin/navitem': typeof AuthenticatedAdminNavitemRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/admin/session': typeof AuthenticatedAdminSessionRoute
  '/admin/user': typeof AuthenticatedAdminUserRoute
  '/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/invitation': typeof AuthenticatedAdminInvitationRoute
  '/_authenticated/admin/member': typeof AuthenticatedAdminMemberRoute
  '/_authenticated/admin/navgroup': typeof AuthenticatedAdminNavgroupRoute
  '/_authenticated/admin/navitem': typeof AuthenticatedAdminNavitemRoute
  '/_authenticated/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/_authenticated/admin/rolenavgroup': typeof AuthenticatedAdminRolenavgroupRoute
  '/_authenticated/admin/session': typeof AuthenticatedAdminSessionRoute
  '/_authenticated/admin/user': typeof AuthenticatedAdminUserRoute
  '/_authenticated/admin/userrolenavgroup': typeof AuthenticatedAdminUserrolenavgroupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/account'
    | '/admin/invitation'
    | '/admin/member'
    | '/admin/navgroup'
    | '/admin/navitem'
    | '/admin/organization'
    | '/admin/rolenavgroup'
    | '/admin/session'
    | '/admin/user'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/sessions'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/admin/account'
    | '/admin/invitation'
    | '/admin/member'
    | '/admin/navgroup'
    | '/admin/navitem'
    | '/admin/organization'
    | '/admin/rolenavgroup'
    | '/admin/session'
    | '/admin/user'
    | '/admin/userrolenavgroup'
    | '/admin/users'
    | '/admin/verification'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/invitation'
    | '/_authenticated/admin/member'
    | '/_authenticated/admin/navgroup'
    | '/_authenticated/admin/navitem'
    | '/_authenticated/admin/organization'
    | '/_authenticated/admin/rolenavgroup'
    | '/_authenticated/admin/session'
    | '/_authenticated/admin/user'
    | '/_authenticated/admin/userrolenavgroup'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verification'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/sessions/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}
export interface FileServerRoutesByFullPath {
  '/api/sessions': typeof ApiSessionsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/users/$id': typeof ApiUsersIdServerRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdServerRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderServerRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityServerRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdServerRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderServerRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityServerRoute
  '/api/admin/navgroup': typeof ApiAdminNavgroupIndexServerRoute
  '/api/admin/navitem': typeof ApiAdminNavitemIndexServerRoute
  '/api/admin/user': typeof ApiAdminUserIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/sessions': typeof ApiSessionsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/users/$id': typeof ApiUsersIdServerRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdServerRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderServerRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityServerRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdServerRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderServerRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityServerRoute
  '/api/admin/navgroup': typeof ApiAdminNavgroupIndexServerRoute
  '/api/admin/navitem': typeof ApiAdminNavitemIndexServerRoute
  '/api/admin/user': typeof ApiAdminUserIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/sessions': typeof ApiSessionsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/users/$id': typeof ApiUsersIdServerRoute
  '/api/admin/navgroup/$id': typeof ApiAdminNavgroupIdServerRoute
  '/api/admin/navgroup/order': typeof ApiAdminNavgroupOrderServerRoute
  '/api/admin/navgroup/visibility': typeof ApiAdminNavgroupVisibilityServerRoute
  '/api/admin/navitem/$id': typeof ApiAdminNavitemIdServerRoute
  '/api/admin/navitem/order': typeof ApiAdminNavitemOrderServerRoute
  '/api/admin/navitem/visibility': typeof ApiAdminNavitemVisibilityServerRoute
  '/api/admin/navgroup/': typeof ApiAdminNavgroupIndexServerRoute
  '/api/admin/navitem/': typeof ApiAdminNavitemIndexServerRoute
  '/api/admin/user/': typeof ApiAdminUserIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/sessions'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/navgroup'
    | '/api/admin/navitem'
    | '/api/admin/user'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/sessions'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/navgroup'
    | '/api/admin/navitem'
    | '/api/admin/user'
  id:
    | '__root__'
    | '/api/sessions'
    | '/api/users'
    | '/api/auth/$'
    | '/api/users/$id'
    | '/api/admin/navgroup/$id'
    | '/api/admin/navgroup/order'
    | '/api/admin/navgroup/visibility'
    | '/api/admin/navitem/$id'
    | '/api/admin/navitem/order'
    | '/api/admin/navitem/visibility'
    | '/api/admin/navgroup/'
    | '/api/admin/navitem/'
    | '/api/admin/user/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSessionsServerRoute: typeof ApiSessionsServerRoute
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAdminNavgroupIdServerRoute: typeof ApiAdminNavgroupIdServerRoute
  ApiAdminNavgroupOrderServerRoute: typeof ApiAdminNavgroupOrderServerRoute
  ApiAdminNavgroupVisibilityServerRoute: typeof ApiAdminNavgroupVisibilityServerRoute
  ApiAdminNavitemIdServerRoute: typeof ApiAdminNavitemIdServerRoute
  ApiAdminNavitemOrderServerRoute: typeof ApiAdminNavitemOrderServerRoute
  ApiAdminNavitemVisibilityServerRoute: typeof ApiAdminNavitemVisibilityServerRoute
  ApiAdminNavgroupIndexServerRoute: typeof ApiAdminNavgroupIndexServerRoute
  ApiAdminNavitemIndexServerRoute: typeof ApiAdminNavitemIndexServerRoute
  ApiAdminUserIndexServerRoute: typeof ApiAdminUserIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/userrolenavgroup': {
      id: '/_authenticated/admin/userrolenavgroup'
      path: '/admin/userrolenavgroup'
      fullPath: '/admin/userrolenavgroup'
      preLoaderRoute: typeof AuthenticatedAdminUserrolenavgroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/user': {
      id: '/_authenticated/admin/user'
      path: '/admin/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AuthenticatedAdminUserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/session': {
      id: '/_authenticated/admin/session'
      path: '/admin/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AuthenticatedAdminSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rolenavgroup': {
      id: '/_authenticated/admin/rolenavgroup'
      path: '/admin/rolenavgroup'
      fullPath: '/admin/rolenavgroup'
      preLoaderRoute: typeof AuthenticatedAdminRolenavgroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organization': {
      id: '/_authenticated/admin/organization'
      path: '/admin/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/navitem': {
      id: '/_authenticated/admin/navitem'
      path: '/admin/navitem'
      fullPath: '/admin/navitem'
      preLoaderRoute: typeof AuthenticatedAdminNavitemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/navgroup': {
      id: '/_authenticated/admin/navgroup'
      path: '/admin/navgroup'
      fullPath: '/admin/navgroup'
      preLoaderRoute: typeof AuthenticatedAdminNavgroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/member': {
      id: '/_authenticated/admin/member'
      path: '/admin/member'
      fullPath: '/admin/member'
      preLoaderRoute: typeof AuthenticatedAdminMemberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invitation': {
      id: '/_authenticated/admin/invitation'
      path: '/admin/invitation'
      fullPath: '/admin/invitation'
      preLoaderRoute: typeof AuthenticatedAdminInvitationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/user/': {
      id: '/api/admin/user/'
      path: '/api/admin/user'
      fullPath: '/api/admin/user'
      preLoaderRoute: typeof ApiAdminUserIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navitem/': {
      id: '/api/admin/navitem/'
      path: '/api/admin/navitem'
      fullPath: '/api/admin/navitem'
      preLoaderRoute: typeof ApiAdminNavitemIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navgroup/': {
      id: '/api/admin/navgroup/'
      path: '/api/admin/navgroup'
      fullPath: '/api/admin/navgroup'
      preLoaderRoute: typeof ApiAdminNavgroupIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navitem/visibility': {
      id: '/api/admin/navitem/visibility'
      path: '/api/admin/navitem/visibility'
      fullPath: '/api/admin/navitem/visibility'
      preLoaderRoute: typeof ApiAdminNavitemVisibilityServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navitem/order': {
      id: '/api/admin/navitem/order'
      path: '/api/admin/navitem/order'
      fullPath: '/api/admin/navitem/order'
      preLoaderRoute: typeof ApiAdminNavitemOrderServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navitem/$id': {
      id: '/api/admin/navitem/$id'
      path: '/api/admin/navitem/$id'
      fullPath: '/api/admin/navitem/$id'
      preLoaderRoute: typeof ApiAdminNavitemIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navgroup/visibility': {
      id: '/api/admin/navgroup/visibility'
      path: '/api/admin/navgroup/visibility'
      fullPath: '/api/admin/navgroup/visibility'
      preLoaderRoute: typeof ApiAdminNavgroupVisibilityServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navgroup/order': {
      id: '/api/admin/navgroup/order'
      path: '/api/admin/navgroup/order'
      fullPath: '/api/admin/navgroup/order'
      preLoaderRoute: typeof ApiAdminNavgroupOrderServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/navgroup/$id': {
      id: '/api/admin/navgroup/$id'
      path: '/api/admin/navgroup/$id'
      fullPath: '/api/admin/navgroup/$id'
      preLoaderRoute: typeof ApiAdminNavgroupIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminInvitationRoute: typeof AuthenticatedAdminInvitationRoute
  AuthenticatedAdminMemberRoute: typeof AuthenticatedAdminMemberRoute
  AuthenticatedAdminNavgroupRoute: typeof AuthenticatedAdminNavgroupRoute
  AuthenticatedAdminNavitemRoute: typeof AuthenticatedAdminNavitemRoute
  AuthenticatedAdminOrganizationRoute: typeof AuthenticatedAdminOrganizationRoute
  AuthenticatedAdminRolenavgroupRoute: typeof AuthenticatedAdminRolenavgroupRoute
  AuthenticatedAdminSessionRoute: typeof AuthenticatedAdminSessionRoute
  AuthenticatedAdminUserRoute: typeof AuthenticatedAdminUserRoute
  AuthenticatedAdminUserrolenavgroupRoute: typeof AuthenticatedAdminUserrolenavgroupRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
  AuthenticatedAdminInvitationRoute: AuthenticatedAdminInvitationRoute,
  AuthenticatedAdminMemberRoute: AuthenticatedAdminMemberRoute,
  AuthenticatedAdminNavgroupRoute: AuthenticatedAdminNavgroupRoute,
  AuthenticatedAdminNavitemRoute: AuthenticatedAdminNavitemRoute,
  AuthenticatedAdminOrganizationRoute: AuthenticatedAdminOrganizationRoute,
  AuthenticatedAdminRolenavgroupRoute: AuthenticatedAdminRolenavgroupRoute,
  AuthenticatedAdminSessionRoute: AuthenticatedAdminSessionRoute,
  AuthenticatedAdminUserRoute: AuthenticatedAdminUserRoute,
  AuthenticatedAdminUserrolenavgroupRoute:
    AuthenticatedAdminUserrolenavgroupRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiUsersServerRouteChildren {
  ApiUsersIdServerRoute: typeof ApiUsersIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersIdServerRoute: ApiUsersIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSessionsServerRoute: ApiSessionsServerRoute,
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAdminNavgroupIdServerRoute: ApiAdminNavgroupIdServerRoute,
  ApiAdminNavgroupOrderServerRoute: ApiAdminNavgroupOrderServerRoute,
  ApiAdminNavgroupVisibilityServerRoute: ApiAdminNavgroupVisibilityServerRoute,
  ApiAdminNavitemIdServerRoute: ApiAdminNavitemIdServerRoute,
  ApiAdminNavitemOrderServerRoute: ApiAdminNavitemOrderServerRoute,
  ApiAdminNavitemVisibilityServerRoute: ApiAdminNavitemVisibilityServerRoute,
  ApiAdminNavgroupIndexServerRoute: ApiAdminNavgroupIndexServerRoute,
  ApiAdminNavitemIndexServerRoute: ApiAdminNavitemIndexServerRoute,
  ApiAdminUserIndexServerRoute: ApiAdminUserIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
