export { default as DepartmentsPage } from './departments-page'
export * from './data/schema'
export * from './hooks/use-departments-query'
export * from './hooks/use-departments-optimistic-update'
export * from './components/departments-provider'
export * from './components/departments-dialogs'
export * from './components/departments-primary-buttons'
export * from './components/department-mutate-dialog'
export * from './components/data-table-row-actions'
